### ISSUE TITLE
It all starts here...

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#1]
Lets start...

**Comment by hello-smile6** [comment]
Hmm, let's get this set up. Here's a shell script you might want to use for setting this up.
```bash
git clone https://github.com/electron/electron-quick-start.git
git clone https://github.com/JaydenDev/Catalyst.git
cd electron-quick-start
rm -rf .git
cd ..
cp electron-quick-start/* Catalyst --update
cd Catalyst
git commit --allow-empty -m "Get Electron-quick-start added"
git push
```
I think that'd work.

**Comment by JaydenDev** [comment]
It's already set up

**Comment by JaydenDev** [comment]
No, this is completely from scratch. No FreeCat code allowed

**Comment by hello-smile6** [comment]
> No, this is completely from scratch. No FreeCat code allowed

I know that it is.

**Comment by JaydenDev** [comment]
Now, we start on the UI. No backend yet, the UI.

**Comment by JaydenDev** [comment]
The index.html file should be the organized focus.
And choosing a CSS framework

**Comment by hello-smile6** [comment]
> The index.html file should be the organized focus. And choosing a CSS framework

Why not use `/dev/null` for a CSS framework?

**Comment by JaydenDev** [comment]
why use a black hole as a CSS framework

**Comment by hello-smile6** [comment]
Hmm, why not make a NodeJS runtime for scratch-vm and expose Electron APIs through extensions? Then we wouldn't have any more errors.

**Comment by hello-smile6** [comment]
> why use a black hole as a CSS framework

Because it's better to use original code.

**Comment by JaydenDev** [comment]
This'll be so much easier with a framework ...

**Comment by hello-smile6** [comment]
> This'll be so much easier with a framework...

Let's make our own framework! Could you move this to a github org?

**Comment by JaydenDev** [comment]
NO! I already said NO!
IM NOT LETTING YOU MAKE A MESS AGAIN

**Comment by hello-smile6** [comment]
> NO! I already said NO! IM NOT LETTING YOU MAKE A MESS AGAIN

Okay, I get it!

**Comment by JaydenDev** [comment]
The point of this redoing of the browser is to NOT make the same mistakes.
Your mistakes repeat if you have any control over anything.

**Comment by hello-smile6** [comment]
> The point of this redoing of the browser is to NOT make the same mistakes. Your mistakes repeat if you have any control over anything.

I'm not asking for control. I'm asking for a 1-person org with just you, similar to @Turbowarp or @llk

**Comment by JaydenDev** [comment]
the focus is getting Catalyst started not making stupid decisions with the repository. Focus on the ACTUAL PROJECT.

**Comment by hello-smile6** [comment]
> the focus is getting Catalyst started not making stupid decisions with the repository. Focus on the ACTUAL PROJECT.

Okay. Just saying, this won't go very well if you abuse potential contributors.

**Comment by JaydenDev** [comment]
I did nothing wrong, just people are distracted by the least important things. Slowing development.

**Comment by hello-smile6** [comment]
> I did nothing wrong, just people are distracted by the least important things. Slowing development.

Hmm, I feel like I'm going to make my own Electron browser instead.

**Comment by JaydenDev** [comment]
Go right along ahead, I'll just fail behind

**Comment by JaydenDev** [comment]
I'll just manage all my repositories when I already struggle to manage them all.

**Comment by hello-smile6** [comment]
> Go right along <del>ahead</del><ins>behind</ins>, I'll just <del>fail</del><ins>succeed</ins> <del>behind</del><ins>ahead</ins>

Corrected your post to reflect reality.

**Comment by JaydenDev** [comment]
I suck at coding back end... the front end is goin great but how the heck do i...

**Comment by hello-smile6** [comment]
> I suck at coding back end... the front end is goin great but how the heck do i...

You don't suck.

**Comment by hello-smile6** [comment]
@JaydenDev Could you look at https://github.com/SpellCheckJS/SpellCheckJS/discussions/3 ?

**Comment by JaydenDev** [comment]
when i click the button it doesn't load the website into webview.. its enabled idk check main.js and index.html

**Comment by hello-smile6** [comment]
> when i click the button it doesn't load the website into webview.. its enabled idk check main.js and index.html

Strange.

**Comment by JaydenDev** [comment]
also check src/ and the javascript files.
why when button press webview no show website in search box

**Comment by hello-smile6** [comment]
> also check src/ and the javascript files. why when button press webview no show website in search box

Not sure.

**Comment by JaydenDev** [comment]
I did it all myself so i probably did something wrong... cann you check the files i listed.

**Comment by hello-smile6** [comment]
> I did it all myself so i probably did something wrong... cann you check the files i listed.

Sure. I'll get a local copy.

**Comment by JaydenDev** [comment]
> > I did it all myself so i probably did something wrong... cann you check the files i listed.
> 
> Sure. I'll get a local copy.

Once it's working I'll get reload back and forward buttons working it's very easy with built in web view functions

**Comment by hello-smile6** [comment]
> > > I did it all myself so i probably did something wrong... cann you check the files i listed.
> > 
> > 
> > Sure. I'll get a local copy.
> 
> Once it's working I'll get reload back and forward buttons working it's very easy with built in web view functions

Okay.

**Comment by webdev03** [comment]
https://tailwindcss.com

**Comment by hello-smile6** [comment]
> https://tailwindcss.com

Agreed.

**Comment by JaydenDev** [comment]
Ninetails uses tailwind so I can't be making a complete copy of the UI

**Comment by hello-smile6** [comment]
> Ninetails uses tailwind so I can't be making a complete copy of the UI

Just don't steal code from them. It's not a complete copy unless you make it that way.

**Comment by kccuber-scratch** [comment]
> @JaydenDev Could you look at [SpellCheckJS/SpellCheckJS#3](https://github.com/SpellCheckJS/SpellCheckJS/discussions/3) ?

please stop distracting. this is why freecat failed to actually go anywhere.

**Comment by JaydenDev** [comment]
Does anybody know why the webview page doesn't change to the website put into the URL bar when the "GO" button is clicked.

**Comment by JaydenDev** [comment]
I found and fixed the issues

**Comment by JaydenDev** [comment]
now its working just gotta get the webview to take full size
