### ISSUE TITLE
JaydenDev please fix the update notifier

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#101]
For versions that contain any letters in them, like `v1.0.0-pre1` in the version for package.json running `Number("1.0.0-pre1")` returns `NaN` which fails to notify the user about an update. Please fix this when you continue to maintain this repository.

**Comment by webdev03** [comment]
@JaydenDev I told you earlier

**Comment by JaydenDev** [comment]
I'll keep this in bind in the next releases

**Comment by webdev03** [comment]
Ok! You can ask me if you have any doubts.
