### ISSUE TITLE
32-bit auto-builds

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#105]
Users like @kccuber need 32 bit builds to run Catalyst, if you could add that to the automatic build system that'd be great.

**Comment by JaydenDev** [comment]
@webdev03

**Comment by kccuber-scratch** [comment]
i dont need a 32 bit build, its just for that 1 old laptop

**Comment by JaydenDev** [comment]
@kccuber-scratch they are nice to have

**Comment by hello-smile6** [comment]
@JaydenDev Please do 32-bit builds!!! Also, statically linked. While you're at it could you build statically linked 32-bit binaries for xorg, fluxbox, and anything else needed for a GUI on https://copy.sh/v86/?profile=buildroot ? I'd greatly appreciate that.

**Comment by webdev03** [comment]
Does github actions have this?

**Comment by JaydenDev** [comment]
> @JaydenDev Please do 32-bit builds!!! Also, statically linked. While you're at it could you build statically linked 32-bit binaries for xorg, fluxbox, and anything else needed for a GUI on https://copy.sh/v86/?profile=buildroot ? I'd greatly appreciate that.

that's repository bloat.

**Comment by webdev03** [comment]
Github actions.. probably doesn't have this..

**Comment by JaydenDev** [comment]
@webdev03 just get 32 bit builds, dont do any of the crap hello-smile is requesting.

**Comment by webdev03** [comment]
I can't build myself, and github actions can't really do it.

**Comment by hello-smile6** [comment]
> > @JaydenDev Please do 32-bit builds!!! Also, statically linked. While you're at it could you build statically linked 32-bit binaries for xorg, fluxbox, and anything else needed for a GUI on https://copy.sh/v86/?profile=buildroot ? I'd greatly appreciate that.
> 
> that's repository bloat.

Was just requesting that as something unrelated to Catalyst. I'm really wanting to run GUI programs on v86 without using dsl or Tiny Core.

> Github actions.. probably doesn't have this..

You can build 32-bit binaries on a 64-bit system. You can also build 64-bit binaries on a 32-bit system.

**Comment by JaydenDev** [comment]
@hello-smile6 v86 is not whats on topic here, this is Catalyst development. This repository and built binaries are for Catalyst ONLY.

We don't care about your silly whatever the heck your doing, just get 32 bit builds in the auto-build system.

**Comment by webdev03** [comment]
How to do that in Electron Forge?

**Comment by JaydenDev** [comment]
> How to do that in Electron Forge?

idk exactly

**Comment by hello-smile6** [comment]
> How to do that in Electron Forge?

Just pass parameters to `electron-forge make`. Read the docs.

**Comment by JaydenDev** [comment]
"read the docs" isn't a helpful statement @hello-smile6

**Comment by JaydenDev** [comment]
@webdev03 Well we'll just have to leave 32 bit users behind on this, 32 bit is obselete anyway

**Comment by hello-smile6** [comment]
> "read the docs" isn't a helpful statement @hello-smile6

Okay, then I'll find the info. Also, you can hide comments instead of deleting them.

**Comment by JaydenDev** [comment]
> > "read the docs" isn't a helpful statement @hello-smile6
> 
> Okay, then I'll find the info. Also, you can hide comments instead of deleting them.

Deleting > Hiding

**Comment by webdev03** [comment]
I'll try to do this.. please wait!

**Comment by JaydenDev** [comment]
@webdev03 is it really possible tho?

**Comment by hello-smile6** [comment]
Here you go.
https://chr15m.github.io/bugout/examples/messageboard.html#bCxAvXzKk2ziQzd66zkCSUg69foyWPcCF5

**Comment by hello-smile6** [comment]
Wait a minute, wrong link.

**Comment by hello-smile6** [comment]
Here's the info.
https://www.electronforge.io/cli#make

**Comment by JaydenDev** [comment]
> Here's the info. https://www.electronforge.io/cli#make

a command would be more useful ...

**Comment by webdev03** [comment]
Got it.

**Comment by hello-smile6** [comment]
```bash
electron-forge make --arch x32
```
Just run that on a 64-bit GitHub Actions Linux runner.

**Comment by JaydenDev** [comment]
> ```shell
> electron-forge make --arch x32
> ```
> 
> Just run that on a 64-bit GitHub Actions Linux runner.

This must include Mac32, Win32, and Linux32

**Comment by hello-smile6** [comment]
> > Here's the info. https://www.electronforge.io/cli#make
> 
> a command would be more useful ...

Stop deleting my comments when they're on-topic!

**Comment by JaydenDev** [comment]
> > > Here's the info. https://www.electronforge.io/cli#make
> > 
> > 
> > a command would be more useful ...
> 
> Stop deleting my comments when they're on-topic!

stop spamming useless comments then...

**Comment by hello-smile6** [comment]
> > ```shell
> > electron-forge make --arch x32
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just run that on a 64-bit GitHub Actions Linux runner.
> 
> This must include Mac32, Win32, and Linux32

https://www.electronforge.io/cli#:~:text=please%20note%20you%20normally%20can%20only%20target%20platform%20X%20from%20platform%20X.
Don't think that's possible. And there's no such thing as 32-bit MacOS, I think.

**Comment by JaydenDev** [comment]
> > > ```shell
> > > electron-forge make --arch x32
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Just run that on a 64-bit GitHub Actions Linux runner.
> > 
> > 
> > This must include Mac32, Win32, and Linux32
> 
> https://www.electronforge.io/cli#:~:text=please%20note%20you%20normally%20can%20only%20target%20platform%20X%20from%20platform%20X. Don't think that's possible. And there's no such thing as 32-bit MacOS, I think.

You think MacOS didn't exist pre-64bit. That's kinda dumb, think before you post stupid comments.

**Comment by webdev03** [comment]
32 bit macOS exists. I am not sure if my latest commit works, can you check?

**Comment by JaydenDev** [comment]
@webdev03 Hold on, I gotta get a fresh cloned copy of the repo.

**Comment by hello-smile6** [comment]
> 32 bit macOS exists. I am not sure if my latest commit works, can you check?

Oh, it does? Should we do ARM64 builds for people like <a href="https://scratch.mit.edu/users/Chiroyce">@Chiroyce</a>?

**Comment by webdev03** [comment]
No, I mean to say, I did in the github action.

**Comment by JaydenDev** [comment]
I had to make a tag.

**Comment by JaydenDev** [comment]
> > 32 bit macOS exists. I am not sure if my latest commit works, can you check?
> 
> Oh, it does? Should we do ARM64 builds for people like [@Chiroyce](https://scratch.mit.edu/users/Chiroyce)?

that would require extensive work

**Comment by hello-smile6** [comment]
> > > 32 bit macOS exists. I am not sure if my latest commit works, can you check?
> > 
> > 
> > Oh, it does? Should we do ARM64 builds for people like [@Chiroyce](https://scratch.mit.edu/users/Chiroyce)?
> 
> that would require extensive work

Wouldn't it just be this?
```
electron-forge make --arch arm64
```
Could we just use a MacOS runner?

**Comment by webdev03** [comment]
ARM64 isn't for github actions.

**Comment by hello-smile6** [comment]
> ARM64 isn't for github actions.

I know, but you should be able to build ARM64 binaries on x64 MacOS, which works on GitHub Actions.

**Comment by JaydenDev** [comment]
@hello-smile6 lets not give people less reasons to not use M1 macs

**Comment by webdev03** [comment]
I don't think it worked...

**Comment by webdev03** [comment]
It's giving the same ones?

**Comment by hello-smile6** [comment]
> @hello-smile6 lets not give people less reasons to not use M1 macs

Why?
<a href="https://www.howtogeek.com/767684/how-to-install-linux-on-apple-silicon/#:~:text=%20How%20to%20Install%20Linux%20on%20an%20M1,can%20also%20create%20your%20own%20VM%2C...%20More%20">Linux is universal...</a>

**Comment by hello-smile6** [comment]
> It's giving the same ones?

What did it say while building?

**Comment by JaydenDev** [comment]
because I don't like Apple

**Comment by hello-smile6** [comment]
> because I don't like Apple

Wrong article, you can actually run Linux natively.

**Comment by JaydenDev** [comment]
just keeping the x86_64 Mac builds so at the very least they aren't being ARM for laptops/PCs fans. ARM is strictly phones and tablets only forever

**Comment by webdev03** [comment]
I use a MacBook Air, please don't discriminate against me lol

**Comment by JaydenDev** [comment]
@webdev03 32 bit building failed, check here:
https://github.com/JaydenDev/Catalyst/runs/4652773189?check_suite_focus=true

**Comment by hello-smile6** [comment]
> I use a MacBook Air, please don't discriminate against me lol

I'll get you some ARM64 builds on my fork.

**Comment by JaydenDev** [comment]
> > I use a MacBook Air, please don't discriminate against me lol
> 
> I'll get you some ARM64 builds on my fork.

they can be built on the official repo fine

**Comment by hello-smile6** [comment]
I know what went wrong. It build x64 twice. Try this.
```
electron-forge make --arch x86
```

**Comment by JaydenDev** [comment]
I'd prefer binaries be built on the official repo, unless the forks aren't a complete copy.

**Comment by JaydenDev** [comment]
> I know what went wrong. It built x64 twice. Try this.
> 
> ```
> electron-forge make --arch x86
> ```

64 bit isn't wanted...

**Comment by hello-smile6** [comment]
> I'd prefer binaries be built on the official repo, unless the forks aren't a complete copy.

I could always run `git pull` on my repo and build every 10 minutes.

**Comment by webdev03** [comment]
It says `x64` in the log. I keep on forgetting which architecture is which, but `x64` is going to be the modern one or `x86`?

**Comment by JaydenDev** [comment]
cant you just

--arch x32

**Comment by webdev03** [comment]
ie32 is what I tried.

**Comment by hello-smile6** [comment]
> > I know what went wrong. It built x64 twice. Try this.
> > ```
> > electron-forge make --arch x86
> > ```
> 
> 64 bit isn't wanted twice tho... you are doing it twice with that command.

I think `x32` is the wrong architecture name. I have a feeling it refers to it as `x86`.

**Comment by webdev03** [comment]
Oh wait, you mean, I had made `--arch=architecture` instead of `--arch architecture`!

**Comment by JaydenDev** [comment]
@webdev03 im pretty sure your correct already tho.

**Comment by hello-smile6** [comment]
> Oh wait, you mean, I had made `--arch=architecture` instead of `--arch architecture`!

Oh, that explains it.

**Comment by JaydenDev** [comment]
no --arch=arch is correct, the docs say

**Comment by hello-smile6** [comment]
> no --arch=arch is correct, the docs say

Hmm, what was that about deletion of a `read the docs` comment? 😄

**Comment by JaydenDev** [comment]
@hello-smile6 i read the docs and provided the information instead of linking docs.

**Comment by hello-smile6** [comment]
> @hello-smile6 i read the docs and provided the information instead of linking docs.

Oh.

**Comment by JaydenDev** [comment]
Neither 1.1 or 2.0 will be ever releasing.
Thank you everyone for your contributions but I will be killing the Catalyst project, forever. I will be archiving soon, if you like Catalyst please either go to Ninetails or another Electron browser.

**Comment by webdev03** [comment]
Catalyst back! @JaydenDev

**Comment by JaydenDev** [comment]
I'm going to remake this issue to declutter the conversation.

**Comment by webdev03** [comment]
#110
