### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#106]
> @webdev03 2.0 adds features 1.1.0 is a patch release Like Chrome or FF
> 

no

node versioning (what you are supposed to be using because electron)

```
M.F.P
```
M = Major (for breaking changes, dramatic changes like whole rewrite)
F = Feature (For new features)
P = Patch (for bug fixes)

you should use this pattern or npm/pnpm/yarn will throw errors one day

Chrome/Firefox would use F.P, which would throw errors if used in package.json

But tbh, @webdev03 is correct.

_Originally posted by @FunctionalMetatable in https://github.com/JaydenDev/Catalyst/issues/98#issuecomment-1001600486_

**Comment by webdev03** [comment]
Reason why, you can do your current thing with a different system, but this is a nodejs project.

**Comment by JaydenDev** [comment]
Closing as solved, because its not an issue at all.

**Comment by webdev03** [comment]
It will be in the future.

**Comment by hello-smile6** [comment]
> Closing as solved, because its not an issue at all.

Then use the "convert to discussion" button.
