### ISSUE TITLE
x86/32 Bit

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#110]

**Comment by webdev03** [comment]
Ok, I think KCCUBER made a pr in Ninetails that can do this. Could we ask KCCUBER to help?

**Comment by JaydenDev** [comment]
well I can't @ him

**Comment by webdev03** [comment]
@kccuber-scratch

**Comment by webdev03** [comment]
Also by the way I don't have access anymore, is this intentional or not?

**Comment by JaydenDev** [comment]
@webdev03 was to make sure nobody unarchived.

**Comment by webdev03** [comment]
Oh, I understand.

**Comment by webdev03** [comment]
Can you @JaydenDev make a release to test?

**Comment by JaydenDev** [comment]
@webdev03 I'm making a release
I gave you write permissions but DONT make releases. I don't like how you label them.

**Comment by webdev03** [comment]
Ok.

**Comment by webdev03** [comment]
Hmm, doesn't seem to build. Just makes for `x64` twice.

**Comment by JaydenDev** [comment]
it failed

**Comment by webdev03** [comment]
It failed, because it isn't building for 32-bit. Anyways, nobody uses 32 bit anymore. And by 2038 nobody will use it?

**Comment by JaydenDev** [comment]
> It failed, because it isn't building for 32-bit. Anyways, nobody uses 32 bit anymore. And by 2038 nobody will use it?

People are stuck with old computers

**Comment by webdev03** [comment]
Hmm. I don't think I can do this, as I can't test it. Can you try `npm run make -- --arch=ia32`?

**Comment by JaydenDev** [comment]
you cant do npm run make with arguments 

also I think the "--" blank argument your adding is the problem.

**Comment by webdev03** [comment]
`--` isn't the problem

**Comment by JaydenDev** [comment]
Issues will not be closed until it is working on all 3 platforms Win/Mac/Linux.

**Comment by webdev03** [comment]
Electron Forge doesn't have Mac support. I'm unsure how to do it on Windows.

**Comment by JaydenDev** [comment]
> Electron Forge doesn't have Mac support for 32 bit. I'm unsure how to do it on Windows.

probobly the same way as you did it on linux
I don't need Mac32

**Comment by webdev03** [comment]
I tried earlier with Windows. As you saw, it didn't work.

**Comment by JaydenDev** [comment]
> I tried earlier with Windows. As you saw, it didn't work.

Well, I guess just make Catalyst good so people switch to Linux.

**Comment by webdev03** [comment]
There are real use cases for Windows. But this isn't the place to have OS wars. Instead, help with the transition away from 32 bit processors, and only provide it for Linux devices.

**Comment by kccuber-scratch** [comment]
I only really need a linux build

**Comment by webdev03** [comment]
(update) I've made it so that beta builds don't have 32 bit builds. Migrate over to another architecture if you want beta builds.

**Comment by JaydenDev** [comment]
@webdev03 this is against what Catalyst is about once again. I don't support architecture or OS discrimination unless it's against Mac M1

**Comment by webdev03** [comment]
OK, but, you are discriminating against Mac 32 and Windows 32.

**Comment by JaydenDev** [comment]
@webdev03 I'm not the one handling auto building...

**Comment by JaydenDev** [comment]
Win32 is hard? You said that. Mac32 is impossible? You said that.

**Comment by JaydenDev** [comment]
also dont comment on closed issues, close this one when your done talking in it.

**Comment by webdev03** [comment]
Done.
