### ISSUE TITLE
Search autocomplete suggestions do not disappear if enter is pressed too soon

### ISSUE THREAD

**Issue by CocoTheMii** [JaydenDev/Catalyst#112]
### Steps to Reproduce

1. Make sure address bar is empty
2. Quickly type anything into the address bar
3. Before the autocomplete suggestions appear, press enter to search

### Expected Result

DuckDuckGo results are displayed as normal.

### Actual Result

DuckDuckGo results are displayed, but are obscured by the autocomplete suggestions, which pop up simultaneously. The suggestions only disappear once you type something else in the address bar.

![Catalyst-bug1](https://user-images.githubusercontent.com/44563370/147866987-56da8694-e3b4-44e5-a58c-6b40a5940248.gif)

**Comment by webdev03** [comment]
OK, I'll fix it.

**Comment by JaydenDev** [comment]
@webdev03, is the one that designed the entire UI, autosuggestions, and tailwind implementation btw!

**Comment by JaydenDev** [comment]
Also, what version of Catalyst is being used here? Is it 1.0, or a pre-release or a beta build?

**Comment by JaydenDev** [comment]
I have been able to reproduce the bug successfully.

**Comment by JaydenDev** [comment]
I shortened the title to not take too lines.

**Comment by JaydenDev** [comment]
@webdev03 how's the fixin' goin?

**Comment by JaydenDev** [comment]
Affected Versions: {Tabby Beta, Tabby, Scottish Fold Beta}

**Comment by JaydenDev** [comment]
@webdev03 you could have a 3 second timeout after the page being changed for the autosuggestion to disappear.

**Comment by webdev03** [comment]
I am going to fix it later.

**Comment by JaydenDev** [comment]
> I am going to fix it later. Pinging me while I am asleep does nothing :P

Please tell what time zone you have to prevent night time pings.

**Comment by webdev03** [comment]
Can you make a fix for it? I can't figure out how.

**Comment by JaydenDev** [comment]
@webdev03 well, I have an idea.

Trigger: After Web Page Finish Loading
Action: If search suggestions still shown hide them after 3 seconds. It doesn't have to know if its hidden or not it just needs to try to.

**Comment by JaydenDev** [comment]
I think it'll work. There's Javascript code online to hide an element. There's listeners for when a page load finishes.

**Comment by webdev03** [comment]
I know how to hide an element @JaydenDev and I have already implemented listeners on page load finish. Working on it

**Comment by JaydenDev** [comment]
So it's fixed?

**Comment by webdev03** [comment]
Yes...

**Comment by JaydenDev** [comment]
ok

**Comment by JaydenDev** [comment]
Bug fixed!

**Comment by JaydenDev** [comment]
confirmed
