### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#115]
The additions to the Contribution Guidelines

- Please don't keep the default commit name that github makes. Change it, to describe very briefly what the commit does. For example, 'Update auto.yml' is not good and doesn't describe what the commit does. 'ci: add 32 bit building to auto releaser' describes the commit much better.
- Do not fight in PRs or issues, that just slows things down.
- Put correct capitalization in your commit names PLEASE @webdev03

**Comment by webdev03** [comment]
OK, you should add this in a `CONTRIBUTING.md` file. It will prompt everyone who wants to contribute too.
Sorry for the default commit names. We could enforce semantic naming with Commitizen...

**Comment by JaydenDev** [comment]
> OK, you should add this in a `CONTRIBUTING.md` file. It will prompt everyone who wants to contribute too. Sorry for the default commit names. We could enforce semantic naming with Github Actions...

Already did that.

**Comment by webdev03** [comment]
I edited it.

**Comment by JaydenDev** [comment]
@webdev03 i dont like what you did.

**Comment by JaydenDev** [comment]
@webdev03 fixed it.

**Comment by webdev03** [comment]
K

**Comment by JaydenDev** [comment]
This isn't an issue to comment on, it's a notice. I will delete all the comments.

**Comment by JaydenDev** [comment]
@webdev03 update the post when updating the file.

**Comment by webdev03** [comment]
Closing because this isn't a real issue. This will still be pinned.

**Comment by JaydenDev** [comment]
Since nobody will be contributing I don't need this pinned.
