### ISSUE TITLE
What features to add next...?

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#12]
?

**Comment by JaydenDev** [comment]
@VelocityDesign wanna go ahead and apply your icon?

**Comment by VelocityDesign** [comment]
Yeah I can get that working

**Comment by JaydenDev** [comment]
k great, i'll be thinking of new features.

**Comment by VelocityDesign** [comment]
You should consider adding the Projects feature w/ kanban boards for feature requests, working on, and finished.

**Comment by JaydenDev** [comment]
i'll get that setup later...
anyway

**Comment by JaydenDev** [comment]
i need the search bar to have just enough width for the 4 buttons to be on the first line

**Comment by VelocityDesign** [comment]
I know HTML so I can work on that. I'm not as good at NodeJS.

**Comment by JaydenDev** [comment]
k!

**Comment by hello-smile6** [comment]
> i need the search bar to have just enough width for the 4 buttons to be on the first line

I could do that in 2 minutes, but I won't.

**Comment by JaydenDev** [comment]
@hello-smile6 ok? so why bother being here then.

**Comment by hello-smile6** [comment]
> @hello-smile6 ok? so why bother being here then.

You've been rude to me. I'm not tolerating it.

**Comment by VelocityDesign** [comment]
> > @hello-smile6 ok? so why bother being here then.
> 
> You've been rude to me. I'm not tolerating it.

If you are not going to help, please do not clutter the forums, discussions, issues, and PRs.

**Comment by JaydenDev** [comment]
@hello-smile6 
look, I try not to be. But when my point never gets across... I have to try harder to get you to NOT break things.

**Comment by hello-smile6** [comment]
> @hello-smile6 look, I try not to be. But when my point never gets across... I have to try harder to get you to NOT break things.

Tell that to @webdev03 , they never even broke anything.

**Comment by JaydenDev** [comment]
Who's idea was it to use prettier?

**Comment by JaydenDev** [comment]
arguments slow progress!

**Comment by hello-smile6** [comment]
> Who's idea was it to use prettier?

Let me find the first comment referencing it.

**Comment by VelocityDesign** [comment]
@JaydenDev @hello-smile6 Can you move this to discussions or some other place? It's irrelevant to this issue...

**Comment by JaydenDev** [comment]
Back on topic
what features?

**Comment by JaydenDev** [comment]
UI Tweaks:

Make buttons consistently positioned no matter what the Window size.

**Comment by hello-smile6** [comment]
> Back on topic what features?

How about a GitHub workflow so people can ban theirselves and avoid going insane?

**Comment by VelocityDesign** [comment]
UI Tweaks:
Add Logo
Use Logo's Color Scheme

**Comment by JaydenDev** [comment]
yeah

**Comment by hello-smile6** [comment]
> yeah

To who?

**Comment by JaydenDev** [comment]
> > yeah
> 
> To who?

not to you for sure

**Comment by hello-smile6** [comment]
> > > yeah
> > 
> > 
> > To who?
> 
> not to you for sure

What?

**Comment by JaydenDev** [comment]
ugh just ignore em.
Catalyst will improve

**Comment by JaydenDev** [comment]
also
https://materializecss.com
read the docs if you ever gotta do front-end changes

**Comment by VelocityDesign** [comment]
Can you clean up the thread a bit?

**Comment by JaydenDev** [comment]
i gotta do a quick change real quick

**Comment by hello-smile6** [comment]
> Can you clean up the thread a bit?

Done. Hid all of my posts as off-topic.

**Comment by JaydenDev** [comment]
I'm not liking the colors of Materialize so much, I don't know how to implement tailwind

**Comment by hello-smile6** [comment]
> I'm not liking the colors of Materialize so much, I don't know how to implement tailwind

Add this to `<head>`
```html
<script src="https://cdn.tailwindcss.com/"></script>
```

**Comment by JaydenDev** [comment]
I gotta do a whole bunch of junk when I use that method.
Is there a direct CSS file I can link?

**Comment by JaydenDev** [comment]
i'd prefer to only have to use one line

**Comment by hello-smile6** [comment]
> I gotta do a whole bunch of junk when I use that method. Is there a direct CSS file I can link?

No, there isn't. You add it, then you use element classes instead of stylesheets. Pretty ridiculous to do, in my opinion. Personally, I'd use dreamcss.

**Comment by JaydenDev** [comment]
ok

**Comment by JaydenDev** [comment]
what tailwind classes should I use for the buttons

**Comment by hello-smile6** [comment]
> what tailwind classes should I use for the buttons

```
width-0 height-0 width-20:dark height-20:dark

**Comment by JaydenDev** [comment]
ok tailwind is doing more harm than good

**Comment by hello-smile6** [comment]
> ok tailwind is doing more harm than good

Time to `rm -rf` it?

**Comment by JaydenDev** [comment]
im ditching CSS frameworks, I'm makin my own now. This is just too painful

**Comment by hello-smile6** [comment]
> im ditching CSS frameworks, I'm makin my own now. This is just too painful

DreamCSS would be good for any webview-based pages.

**Comment by VelocityDesign** [comment]
I'm decent at CSS. I could help with style if you'd like.
My site (Built from scratch): https://jtechnologies.xyz/

**Comment by JaydenDev** [comment]
Well I'll do the buttons wanna do the search bar?

**Comment by VelocityDesign** [comment]
Sure

**Comment by VelocityDesign** [comment]
Do you want me to implement something like the safari accent color when I do?

**Comment by hello-smile6** [comment]
@VelocityDesign Not all by you, it looks like.
```html
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
```

**Comment by VelocityDesign** [comment]
> @VelocityDesign Not all by you, it looks like.
> 
> ```
> <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
> ```

That's just something that CF put in there. I don't have anything else.

**Comment by JaydenDev** [comment]
Well I'm trying to style the buttons and it already sucks
ugh
cant even see the buttons lol

**Comment by VelocityDesign** [comment]
Want me to do it?

**Comment by JaydenDev** [comment]
sure the file is styles.css

**Comment by JaydenDev** [comment]
darn i make a css framework every time i write css...

**Comment by webdev03** [comment]
can't you use tailwind jit?

**Comment by JaydenDev** [comment]
i've tried tailwind its a mess using it

**Comment by JaydenDev** [comment]
I've tried dream.css as well.

**Comment by hello-smile6** [comment]
> > @VelocityDesign Not all by you, it looks like.
> > ```
> > <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
> > ```
> 
> That's just something that CF put in there. I don't have anything else.

Huh.
```
<script type="text/javascript" src="/ynhtheme/custom_portal.js"></script>
```
```
<link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css">
```
https://forum.yunohost.org/t/content-security-policy-problem-with-custom-webapp/8161

**Comment by JaydenDev** [comment]
stop exposing people and just do something else

**Comment by JaydenDev** [comment]
@VelocityDesign you can make a pr and mark it as unfinished so i can see progress.

**Comment by hello-smile6** [comment]
> stop exposing people and just do something else

Fine. :( I'll go work on @SpellCheckJS

**Comment by JaydenDev** [comment]
Darn avoiding stealing code from other projects makes everything hard.
I'm much better at pressing CTRL + C and CTRL + V than I am at coding.

**Comment by JaydenDev** [comment]
i want the forward reload and back buttons to be styled similarly to Ninetails.. not exact.

**Comment by hello-smile6** [comment]
> Darn avoiding stealing code from other projects makes everything hard. I'm much better at pressing CTRL + C and CTRL + V than I am at coding.

Huh. Just install Docker and run a custom build of vscode (or, if you insist, vim) in docker which doesn't allow copy/paste and disable networking in docker. Then you won't be able to copy and paste as easily.

**Comment by JaydenDev** [comment]
thats not what i meant.

**Comment by hello-smile6** [comment]
> thats not what i meant.

Okay :(

**Comment by JaydenDev** [comment]
While UI Design is being handled by @VelocityDesign 
I'm squashing bugs.
Tabs though... tabs umm tabs. How the heck am i gonna do tabs.

**Comment by hello-smile6** [comment]
> While UI Design is being handled by @VelocityDesign I'm squashing bugs. Tabs though... tabs umm tabs. How the heck am i gonna do tabs.

```bash
dd if=ninetails of=Catalyst
```

**Comment by JaydenDev** [comment]
I'm not copying code, especially without permission.

**Comment by JaydenDev** [comment]
Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.

**Comment by hello-smile6** [comment]
> Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.

```bash
cd
mkdir idk
cd idk
git clone "https://github.com/JaydenDev/catalyst.git"
git clone "https://github.com/MystPi/ninetails.git"
tar czf ninetails.tar.gz --exclude ".git" ninetails
cd catalyst
git rm -r .
cd ..
tar -xf ninetails.tar.gz -C catalyst
cd catalyst
git commit --allow-empty -m "Ta-da!"
git push
```
That's all it takes. Just run the shell script. 😄 Just putting it out there. If there are syntax issues, tell me and I'll fix them.

**Comment by JaydenDev** [comment]
> > Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.
> 
> ```bash
> cd
> mkdir idk
> cd idk
> git clone "https://github.com/JaydenDev/catalyst.git"
> git clone "https://github.com/MystPi/ninetails.git"
> tar czf ninetails.tar.gz --exclude ".git" ninetails
> cd catalyst
> git rm -r .
> cd ..
> tar -xf ninetails.tar.gz -C catalyst
> cd catalyst
> git commit --allow-empty -m "Ta-da!"
> git push
> ```
> That's all it takes. Just run the shell script. 😄 Just putting it out there. If there are syntax issues, tell me and I'll fix them. 

Not doing that, not copying code is stupid

**Comment by hello-smile6** [comment]
> > > Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.
> > 
> > 
> > ```shell
> > cd
> > mkdir idk
> > cd idk
> > git clone "https://github.com/JaydenDev/catalyst.git"
> > git clone "https://github.com/MystPi/ninetails.git"
> > tar czf ninetails.tar.gz --exclude ".git" ninetails
> > cd catalyst
> > git rm -r .
> > cd ..
> > tar -xf ninetails.tar.gz -C catalyst
> > cd catalyst
> > git commit --allow-empty -m "Ta-da!"
> > git push
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's all it takes. Just run the shell script. 😄 Just putting it out there. If there are syntax issues, tell me and I'll fix them.
> 
> Not doing that, copying code is stupid
> copying the entire repo, on the other hand, isn't.

I agree. When something doesn't work, just fork your competitor.

**Comment by JaydenDev** [comment]
> > > > Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.
> > > 
> > > 
> > > ```shell
> > > cd
> > > mkdir idk
> > > cd idk
> > > git clone "https://github.com/JaydenDev/catalyst.git"
> > > git clone "https://github.com/MystPi/ninetails.git"
> > > tar czf ninetails.tar.gz --exclude ".git" ninetails
> > > cd catalyst
> > > git rm -r .
> > > cd ..
> > > tar -xf ninetails.tar.gz -C catalyst
> > > cd catalyst
> > > git commit --allow-empty -m "Ta-da!"
> > > git push
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That's all it takes. Just run the shell script. 😄 Just putting it out there. If there are syntax issues, tell me and I'll fix them.
> > 
> > Not doing that, copying code is stupid
> > copying the entire repo, on the other hand, isn't.
> 
> I agree. When something doesn't work, just fork your competitor.

Lmao

**Comment by JaydenDev** [comment]
haters suck

**Comment by hello-smile6** [comment]
> haters suck

???

**Comment by hello-smile6** [comment]
> > > > > Plus the structure of Ninetails's code is far different. I'd have to modify the code a lot anyway to get it to work.
> > > > 
> > > > 
> > > > ```shell
> > > > cd
> > > > mkdir idk
> > > > cd idk
> > > > git clone "https://github.com/JaydenDev/catalyst.git"
> > > > git clone "https://github.com/MystPi/ninetails.git"
> > > > tar czf ninetails.tar.gz --exclude ".git" ninetails
> > > > cd catalyst
> > > > git rm -r .
> > > > cd ..
> > > > tar -xf ninetails.tar.gz -C catalyst
> > > > cd catalyst
> > > > git commit --allow-empty -m "Ta-da!"
> > > > git push
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > That's all it takes. Just run the shell script. 😄 Just putting it out there. If there are syntax issues, tell me and I'll fix them.
> > > 
> > > 
> > > Not doing that, copying code is stupid
> > > copying the entire repo, on the other hand, isn't.
> > 
> > 
> > I agree. When something doesn't work, just fork your competitor.
> 
> Lmao

Why not?

**Comment by VelocityDesign** [comment]
> > > @VelocityDesign Not all by you, it looks like.
> 
> > > ```
> 
> > > <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
> 
> > > ```
> 
> > 
> 
> > That's just something that CF put in there. I don't have anything else.
> 
> 
> 
> Huh.
> 
> ```
> 
> <script type="text/javascript" src="/ynhtheme/custom_portal.js"></script>
> 
> ```
> 
> ```
> 
> <link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css">
> 
> ```
> 
> https://forum.yunohost.org/t/content-security-policy-problem-with-custom-webapp/8161
> 
> ```javascript
> 
> > "yunohost".replace("host","").replace("u","")
> 
> ynh
> 
> ```
I use YunoHost as a port forwarder.

**Comment by hello-smile6** [comment]
> > > > @VelocityDesign Not all by you, it looks like.
> > 
> > 
> > > >
> > 
> > 
> > > > <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > That's just something that CF put in there. I don't have anything else.
> > 
> > 
> > Huh.
> > ```
> > 
> > <script type="text/javascript" src="/ynhtheme/custom_portal.js"></script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > <link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://forum.yunohost.org/t/content-security-policy-problem-with-custom-webapp/8161
> > ```js
> > > "yunohost".replace("host","").replace("u","")
> > 
> > ynh
> > ```
> 
> I use YunoHost as a port forwarder.

Why not use https://github.com/binwiederhier/natter?

**Comment by JaydenDev** [comment]
off topic

**Comment by hello-smile6** [comment]
> off topic

Sorry
