### ISSUE TITLE
Features for use of Scratch Website with Catalyst

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#122]
### Discussed in https://github.com/JaydenDev/Catalyst/discussions/121

<div type='discussions-op-text'>

<sup>Originally posted by **JaydenDev** January  3, 2022</sup>
Goals
## Scratch Forums Image Uploader Implementation
- Copy Paste, image to scratch uploads link
- Button to add image to post
## Scratch 2.0 > 3.0
- Convert web pages with 2.0 styling to 3.0 styling
## Scratch Dark Mode</div>

**Comment by JaydenDev** [comment]
@webdev03 you know how the Scratch Addons extension and the scratch API works RIGHT!?

**Comment by JaydenDev** [comment]
very sorry for the ping, I just now noticed its 6 AM in NZ.

**Comment by webdev03** [comment]
It's ok!

**Comment by webdev03** [comment]
I think this should be done when we eventually have WebExtensions support. I'll work on userscripts later.

**Comment by Mbrick2** [comment]
lets just use the scratch addons code and give credit like turbowarp.

**Comment by webdev03** [comment]
Catalyst isn't just for Scratch Users. Useless scripts for non-scratch users.

**Comment by JaydenDev** [comment]
> Catalyst isn't just for Scratch Users. Useless scripts for non-scratch users.

It can be optional and disabled by default or be an addon available for scratch users.

**Comment by JaydenDev** [comment]
> lets just use the scratch addons code and give credit like turbowarp. 

It's in chrome and Firefox format. Catalyst doesn't even have extensions

**Comment by webdev03** [comment]
I think something like TamperMonkey Userscripts would be nice.

**Comment by webdev03** [comment]
#127 should be able to do a bit of this, but not fully resolve it.

**Comment by JaydenDev** [comment]
Too hard to implement

**Comment by JaydenDev** [comment]
not doing this
