### ISSUE TITLE
Design Changes for 2.0 (Scottish Fold)

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#125]
## Goals

- [x] Make each bookmark in bookmark bar be seperated from the bar itself. 
This just means contrast the clickable bookmark from the bar. Have the actual bar be the background, and the bookmarks have its own background.

**Comment by JaydenDev** [comment]
To explain the change for bookmarks. Look at the tabs. Foreground: The tabs themselves. Background: The bar itself. Gonna make the bookmarks be just like that.

**Comment by webdev03** [comment]
OK

**Comment by JaydenDev** [comment]
Some extras
## Show Catalyst version in settings panel
## Have button to rerun update checking function.

**Comment by JaydenDev** [comment]
#126

**Comment by kccuber-scratch** [comment]
yep, i suggested the bookmark background thing before you temporarily canceled catalyst: https://github.com/JaydenDev/Catalyst/pull/91#issuecomment-1001063464

**Comment by webdev03** [comment]
https://github.com/JaydenDev/Catalyst/commit/6d36de4ac34f131bc3446c417607f5cef1350036

**Comment by JaydenDev** [comment]
@webdev03 great, it works! but please make a PR next time so I can better investigate and test your code.

**Comment by webdev03** [comment]
Ok, sorry! I'll make new branches from now on.

**Comment by JaydenDev** [comment]
Every design change for 2.0 has been done! Now what features for 2.0 idk.

**Comment by webdev03** [comment]
I don't think we have to have a million features. Well, Find could be one that I can try to implement.
