### ISSUE TITLE
M1 Build User Submission.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#130]
Submit your M1 packages here!

**Comment by webdev03** [comment]
I already told you that GitHub Actions doesn't have M1

**Comment by JaydenDev** [comment]
> I already told you that GitHub Actions doesn't have M1

oh... users will have to contribute then.

**Comment by webdev03** [comment]
Why'd you just change the title @JaydenDev

**Comment by JaydenDev** [comment]
> Why'd you just change the title @JaydenDev

it's called post recycling.

**Comment by webdev03** [comment]
How will you verify these aren't viruses?

**Comment by webdev03** [comment]
@JaydenDev close

**Comment by webdev03** [comment]
@JaydenDev close

**Comment by JaydenDev** [comment]
> How will you verify these aren't viruses?

You trust the process that's what.

**Comment by JaydenDev** [comment]
they are already automatic
