### ISSUE TITLE
@webdev03 it is neccesary that this feature be added. Please continue to write it.

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#132]
@webdev03 it is neccesary that this feature be added. Please continue to write it.

__Originally posted by @JaydenDev in https://github.com/JaydenDev/Catalyst/pull/127#issuecomment-1005137092__

Sorry I won't

**Comment by JaydenDev** [comment]
> @webdev03 it is neccesary that this feature be added. Please continue to write it.
> 
> **Originally posted by @JaydenDev in [#127 (comment)](https://github.com/JaydenDev/Catalyst/pull/127#issuecomment-1005137092)**
> 
> Sorry I won't

ok fine then, btw if I really wanted to I could force merge it but I won't. Also reply to the post instead of making issue posts please.

**Comment by webdev03** [comment]
I couldn't reply, the button didn't work. You locked it.

**Comment by JaydenDev** [comment]
ok...?
