### ISSUE TITLE
Optional Opt-In Auto Updates.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#135]
For all platforms obviously!

**Comment by webdev03** [comment]
not possible
and you dont have money to get the certificates
@JaydenDev close?

**Comment by JaydenDev** [comment]
> not possible and you dont have money to get the certificates @JaydenDev close?

wdym certificates?

**Comment by webdev03** [comment]
you have to get signing certificates

**Comment by webdev03** [comment]
on mac I mean, on windows you may be able to set it up. you should get a mac and pay for developer program if you want it on mac.

**Comment by JaydenDev** [comment]
> you have to get signing certificates

on Mac you just install the DMG just fine.

**Comment by JaydenDev** [comment]
Also I can't (and won't) get a Mac, or pay for a developer program.

**Comment by webdev03** [comment]
then pay 400 dollars for a windows certificate

**Comment by webdev03** [comment]
and the dmg still requires you to accept a scary warning

**Comment by JaydenDev** [comment]
> and the dmg still requires you to accept a scary warning

oh well then apple programs. Also I'm not paying anything for any certificate just don't be stupid or scared and think its a virus.

**Comment by webdev03** [comment]
do you realise that its really hard to get rid of the warning for the average user?

**Comment by webdev03** [comment]
anyways im gonna not contribute anymore

**Comment by JaydenDev** [comment]
> do you realise that its really hard to get rid of the warning for the average user?

do you realize I don't need to?

**Comment by JaydenDev** [comment]
> anyways im gonna not contribute anymore

just because I won't spend hundreds on certificates and pay a stupid money hungry company money for an overpriced piece of Aluminum, overpriced parts, and be locked into a stupid ecosystem?

**Comment by webdev03** [comment]
im not contributing because i dont like contributing, thats all. i never specified that it was because you arent going to waste your money on certificates. but saying it is possible when it is impossible or at best possible with some major changes

**Comment by JaydenDev** [comment]
> im not contributing because i dont like contributing, thats all. i never specified that it was because you arent going to waste your money on certificates. but saying it is possible when it is impossible or at best possible with some major changes

Well, don't expect big features. Only bug fixes from now on. You could easily guess why.

**Comment by webdev03** [comment]
@JaydenDev could you do this?

**Comment by JaydenDev** [comment]
> @JaydenDev could you do this?
No

**Comment by JaydenDev** [comment]
costs too much

**Comment by webdev03** [comment]
better solution: put it on linux package managers, winget, and homebrew?
