### ISSUE TITLE
a long list of bugs for somebody to fix? :(

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#143]
youtube comments dont load
sometimes tabs get locked up and cant be used anymore.

**Comment by kccuber-scratch** [comment]
1. What's the user agent that `navigator.userAgent` reports?
2. Probably a memory leak

**Comment by webdev03** [comment]
> What's the user agent that `navigator.userAgent` reports?

can be changed in preferences

**Comment by kccuber-scratch** [comment]
> > What's the user agent that `navigator.userAgent` reports?
> 
> can be changed in preferences

screenshot? I dont use catalyst myself

**Comment by JaydenDev** [comment]
well how to remove Catalyst/1.1.2 from the UA?

**Comment by JaydenDev** [comment]
btw nobody commit to main I have a PR going

**Comment by JaydenDev** [comment]
its a design PR but who cares its the wrong year anyway!

**Comment by kccuber-scratch** [comment]
> well how to remove Catalyst/1.1.2 from the UA?

How ninetails does it.

**Comment by JaydenDev** [comment]
@kccuber-scratch I mean so that a big company's browsers's UA can be injected with no change.

**Comment by JaydenDev** [comment]
#152 also exists as well :(

**Comment by kccuber-scratch** [comment]
> @kccuber-scratch I mean so that a big company's browsers's UA can be injected with no change.

no idea, i browsed thorugh ninetails code but couldn't fins anything

**Comment by webdev03** [comment]
why is this marked with the `javascript` label? that's for dependabot

**Comment by webdev03** [comment]
By the way, the `liberty` issue should be fixed (reinstall deps). It was due to Color JS having an infinite loop. https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by VelocityDesign** [comment]
Oh yeah looks like we got hit by the sabatoge.

**Comment by JaydenDev** [comment]
> why is this marked with the `javascript` label? that's for dependabot

because Catalyst is like half javascript

**Comment by webdev03** [comment]
sabotage??

**Comment by JaydenDev** [comment]
c a n
t h e s e
b u g s
g e t 
f i x e d
?

**Comment by hello-smile6** [comment]
> sabotage??

Making a PR.

**Comment by Steb03** [comment]
> well how to remove Catalyst/1.1.2 from the UA?

What's wrong with Ukraine?

**Comment by hello-smile6** [comment]
> > well how to remove Catalyst/1.1.2 from the UA?
> 
> What's wrong with Ukraine?

User agent string

**Comment by Steb03** [comment]
> > > well how to remove Catalyst/1.1.2 from the UA?
> > 
> > 
> > What's wrong with Ukraine?
> 
> User agent string

Ok, because UA stands for Ukraine
