### ISSUE TITLE
Tailwind CSS Implementation

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#15]

**Comment by JaydenDev** [comment]
This is being handled by @webdev03

**Comment by hello-smile6** [comment]
Then assign it to them

**Comment by webdev03** [comment]
Fixed by #16

**Comment by JaydenDev** [comment]
Alright, now I will start researching the documentation to make the new UI.

**Comment by JaydenDev** [comment]
It looks like @webdev03 did make the UI but I'm not seeing it for some reason...

**Comment by JaydenDev** [comment]
i just see a regular no CSS page

**Comment by JaydenDev** [comment]
I'm dumb, I had to run npm run dev

**Comment by hello-smile6** [comment]
> i just see a regular no CSS page

Screenshot?

**Comment by JaydenDev** [comment]
Just gotta add the forward, back, and reload buttons

**Comment by webdev03** [comment]
Yeah you need to run `npm run dev` instead of the old `npm run start` :)

**Comment by hello-smile6** [comment]
I'll alias `start` as `dev`

**Comment by webdev03** [comment]
No DON'T!
That will BREAK IT!

**Comment by webdev03** [comment]
THE NPM RUN DEV COMMAND RELIES ON NPM RUN START AND NPM RUN TAILWIND @hello-smile6 sorry for being caps lock

**Comment by JaydenDev** [comment]
Can you build on your earlier tailwind PR and add the forward back and reload buttons back?

**Comment by hello-smile6** [comment]
> THE NPM RUN DEV COMMAND RELIES ON NPM RUN START AND NPM RUN TAILWIND @hello-smile6 sorry for being caps lock

OBVIOUSLY!

**Comment by webdev03** [comment]
https://github.com/JaydenDev/Catalyst/issues/15#issuecomment-997497157

**Comment by hello-smile6** [comment]
> THE NPM RUN DEV COMMAND RELIES ON NPM RUN START AND NPM RUN TAILWIND @hello-smile6 sorry for being caps lock

Just realized

**Comment by JaydenDev** [comment]
I think its simple enough for me to readd the buttons myself... i hope

**Comment by webdev03** [comment]
You should do it on play.tailwindcss.com it will help!

**Comment by JaydenDev** [comment]
errrrrr ummm ohhhh' esfdfds
the icons dont work

**Comment by JaydenDev** [comment]
ive pushed my changes
git pull and run it  you'll see the problem.

**Comment by webdev03** [comment]
Hmm. let me see.

**Comment by JaydenDev** [comment]
the buttons look wrong but they do their functions just fine.

**Comment by webdev03** [comment]
Which buttons?

**Comment by hello-smile6** [comment]
```bash
npm i font-awesome
```

**Comment by hello-smile6** [comment]
> ```shell
> npm i font-awesome
> ```

For once, I'm not writing a whole shell script.
<details>
<summary>Test</summary>
It works!!!
</details>

**Comment by JaydenDev** [comment]
oh was font awesome removed from package.json?

**Comment by JaydenDev** [comment]
i installed it and it still doesnt show the icons

**Comment by webdev03** [comment]
Hmm...

**Comment by hello-smile6** [comment]
Don't apply the classes to the `<i>`. Apply them to the `<button>`.

**Comment by JaydenDev** [comment]
oh ok
btw @webdev03 
your electron-forge PR works I successfuly built working binaries

**Comment by webdev03** [comment]
I don't know if MystPi would like it as now that we have Tailwind we are so close to copying, but we could implement automatic builds...

**Comment by JaydenDev** [comment]
yeah we are a bit too close

just get the buttons fixed and I'll release a the bi-daily beta build

**Comment by hello-smile6** [comment]
> I don't know if MystPi would like it as now that we have Tailwind we are so close to copying, but we could implement automatic builds...

@MystPi _Do_ you like it?

**Comment by JaydenDev** [comment]
*the button icons

**Comment by JaydenDev** [comment]
> > I don't know if MystPi would like it as now that we have Tailwind we are so close to copying, but we could implement automatic builds...
> 
> @MystPi _Do_ you like it?

**Comment by webdev03** [comment]
How do the button icons work? Font awesome? Also the browsing doesn't work..

**Comment by JaydenDev** [comment]
font awesome yes

**Comment by webdev03** [comment]
OK.

**Comment by JaydenDev** [comment]
Could you post screenshots of whats goin in dev console

**Comment by JaydenDev** [comment]
make a new issue post, im closing this one as fixed.

**Comment by hello-smile6** [comment]
> make a new issue post, im closing this one as fixed.

Is it fixed?

**Comment by webdev03** [comment]
We already added Tailwind.

**Comment by hello-smile6** [comment]
> We already added Tailwind.

Oh

**Comment by MystPi** [comment]
> > I don't know if MystPi would like it as now that we have Tailwind we are so close to copying, but we could implement automatic builds...
> 
> @MystPi _Do_ you like it?

Anyone can use Tailwind; I don't care. Just don't take anything from Ninetails.
**Also please stop mentioning me on repos I don't contribute to!**
