### ISSUE TITLE
auto builds have wrong time in tag/version name

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#155]
### Steps to reproduce the issue?

just look at the auto builds and their release names

### What happened?

i expected to see a real date from the timezone gh actions uses not one from 2 weeks ago

### Version

n/a

**Comment by JaydenDev** [comment]
you made the entire build system, you know how to fix it.

**Comment by webdev03** [comment]
i dont know how to fix it

**Comment by JaydenDev** [comment]
I don't care if your contributing or not well too bad because Catalyst isn't getting any updates any time soon because of this.
