### ISSUE TITLE
FOSS Marketing???

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/Catalyst#17]
@JaydenDev What the f*** is going on, are you about to start adding telemetry to releases?
https://github.com/JaydenDev/Catalyst/tree/master/marketing

**Comment by webdev03** [comment]
No, not in that sense, I think it is icons and stuff.

**Comment by JaydenDev** [comment]
yeah its icons and stuff
I don't know any word for it

**Comment by JaydenDev** [comment]
@hello-smile6 assumption is stupid LMAO

**Comment by hello-smile6** [comment]
> No, not in that kind of way of spending millions on advertisements, I think it is icons and stuff.

Oh, then could @JaydenDev fix it?
```bash
cd /tmp
mkdir catalyst
cd catalyst
git clone https://github.com/JaydenDev/catalyst.git
cd catalyst
mv marketing assets
git commit --allow-empty -m "Fix directory name"
git push
cd ../..
rm -rf catalyst
```

**Comment by hello-smile6** [comment]
> @hello-smile6 assumption is stupid LMAO

Sorry
