### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by Mbrick2** [JaydenDev/Catalyst#179]
@JaydenDev could you please put screenshots with each release

**Comment by Mbrick2** [comment]
@JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev

**Comment by JaydenDev** [comment]
> @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev @JaydenDev

The more you spam, the longer I'll take to do it.

**Comment by 3DSdev** [comment]
stop spamming
