### ISSUE TITLE
Packaging with Electron-Forge

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#18]

**Comment by webdev03** [comment]
I can work on it :smile:

**Comment by hello-smile6** [comment]
Me too

**Comment by webdev03** [comment]
(You can assign me!)

**Comment by hello-smile6** [comment]
What, how were we assigned? We don't have push access!

**Comment by JaydenDev** [comment]
Just make a PR... I don't want Catalyst to be a mess as well.

**Comment by hello-smile6** [comment]
No, how did it let you?

**Comment by JaydenDev** [comment]
oh... I did it... silently... in the background while nobody was looking.

**Comment by hello-smile6** [comment]
Done!!! I win!

**Comment by hello-smile6** [comment]
> oh... I did it... silently... in the background while nobody was looking.

Did what?

**Comment by JaydenDev** [comment]
assigned developers to the issue
btw you didnt finish it, there's way more you have to add to get building to work

**Comment by hello-smile6** [comment]
> assigned developers to the issue btw you didnt finish it, there's way more you have to add to get building to work

Did you try it?

**Comment by JaydenDev** [comment]
no because you didnt even finish the PR

**Comment by JaydenDev** [comment]
take a look at the package.json in the freecat repo to see what your missing

**Comment by JaydenDev** [comment]
also dont modify the npm start alias as npm dev depends on it

**Comment by hello-smile6** [comment]
> take a look at the package.json in the freecat repo to see what your missing

Okay, https://github.com/JaydenDev/freecat

**Comment by hello-smile6** [comment]
> also dont modify the npm start alias as npm dev depends on it

Check ninetails

**Comment by webdev03** [comment]
No!
Do not modify `npm start` in any way shape or form!

**Comment by hello-smile6** [comment]
> No! Do not modify `npm start` in any way shape or form!

CHECK NINETAILS!!!

**Comment by webdev03** [comment]
Ninetails is different. I will see.

**Comment by hello-smile6** [comment]
> No! Do not modify `npm start` in any way! @JaydenDev is right. Building works, I tried it on my macbook.



> 

Electron == electron

**Comment by webdev03** [comment]
Oh, now I know what you mean.

**Comment by JaydenDev** [comment]
Ninetails has a completely different system of inner workings

**Comment by hello-smile6** [comment]
> Ninetails has a completely different system of inner workings

lol

**Comment by hello-smile6** [comment]
> Ninetails has a completely different system of inner workings

@MystPi Is this correct?

**Comment by MystPi** [comment]
> > Ninetails has a completely different system of inner workings
> 
> @MystPi Is this correct?

Please don't mention me on repos I don't contribute to.

**Comment by hello-smile6** [comment]
> > > Ninetails has a completely different system of inner workings
> > 
> > 
> > @MystPi Is this correct?
> 
> Please don't mention me on repos I don't contribute to.

Sorry
