### ISSUE TITLE
update checker messed up

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#187]
When running 1.2.0 it says an update is available for 1.1.12 when 1.2.0 is in fact the latest release

**Comment by webdev03** [comment]
The update checker wasn't designed to handle more than 2 digits at the end.. hm....

**Comment by JaydenDev** [comment]
> The update checker wasn't designed to handle more than 2 digits at the end.. hm....

well that likely wont happen again with the healthy flow of new feature updates!

**Comment by JaydenDev** [comment]
In the next point release I'll temp disable update checking til a fix is found.

**Comment by webdev03** [comment]
Just remove the releases with more than 3 digits

**Comment by JaydenDev** [comment]
> Just remove the releases with more than 3 digits

No, removing releases is not an option. Also, triple digit releases will never be uncommon, releases get patches you know..
