### ISSUE TITLE
Preload script is mostly useless

### ISSUE THREAD

**Issue by ScolderCreations** [JaydenDev/Catalyst#189]
https://github.com/JaydenDev/Catalyst/blob/2b28a5c2ae26f8036b4da8611a77b16f4a041952/main/preload.js#L10

This is for the default Electron project, and doesn’t seem to be used in Catalyst.

**Comment by ScolderCreations** [comment]
Don’t even get me started with the renderer script… It’s just comments.

**Comment by JaydenDev** [comment]
I'm sure the preload is used to get {version} working
Renderer script is useless though.

**Comment by webdev03** [comment]
Preload isn't used to get the version used in user agent.

By the way, I could try to help you with getting plugins to go in `~/Library/Application Support/Catalyst/plugins` if you want.

**Comment by JaydenDev** [comment]
> Preload isn't used to get the version used in user agent.

kk
