### ISSUE TITLE
[Bug]: Won't open on macos

### ISSUE THREAD

**Issue by Steve0Greatness** [JaydenDev/Catalyst#201]
### Steps to reproduce the issue?

1. Use Mac OS
2. Try opening the DMG

### What happened?

<img width="420" alt="'catalyst' cannot be opened because it is from an unidentified developer; macOS cannot verify that this app is free from malware." src="https://user-images.githubusercontent.com/75220768/160982458-fe337af4-3491-4ff2-bfa0-819f36acc500.png">

I think it speaks for itself

### Your environment (if applicable)

MacOS

### Version

current version

**Comment by webdev03** [comment]
That's because @JaydenDev won't spend $200 NZD every year. Just right click the DMG and press Open if you need to bypass that.
