### ISSUE TITLE
pluginWorker.js filesystem access

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#212]
pluginWorker.js must be given filesystem access to load plugins without recompiling. Any ideas?

**Comment by Darth-Ness** [comment]
For plugins I would recommend not saving them locally. Instead have a list of them stored in local storage or something, then fetch them on startup. Make sure add-on fetching does not block the the app from rendering.

**Comment by Darth-Ness** [comment]
> > For plugins I would recommend not saving them locally. Instead have a list of them stored in local storage or something, then fetch them on startup. Make sure add-on fetching does not block the the app from rendering.
> 
> Saving plugins locally in the Catalyst directory is literally the only way to load plugins without recompiling.

No, I meant if plugins were downloaded from catalyst.plugins.com (Just an example) everytime someone downloads a plugin, it saves the link to the plugin in local storage. Then on browser start up, using those links. Catalyst reinstalls all of those plugins.
Here is an idea of what that would look like in code.

```javascript
if (site == "catalyst.plugins.com) {
    //Insert a click listener onto the install button in the webview.
    localStorage.setItem('pluginList',  webview.getUrl); 
    //Catalyst would probably have to add that to the list by getting the current list then adding the url to it 
}
```

**Comment by JaydenDev** [comment]
> > > For plugins I would recommend not saving them locally. Instead have a list of them stored in local storage or something, then fetch them on startup. Make sure add-on fetching does not block the the app from rendering.
> > 
> > 
> > Saving plugins locally in the Catalyst directory is literally the only way to load plugins without recompiling.
> 
> No, I meant if plugins were downloaded from catalyst.plugins.com (Just an example) everytime someone downloads a plugin, it saves the link to the plugin in local storage. Then on browser start up, using those links. Catalyst reinstalls all of those plugins. Here is an idea of what that would look like in code.
> 
> ```js
> if (site == "catalyst.plugins.com) {
>     //Insert a click listener onto the install button in the webview.
>     localStorage.setItem('pluginList',  webview.getUrl); 
>     //Catalyst would probably have to add that to the list by getting the current list then adding the url to it 
> }
> ```
I don't see how this would work. Also I would have to host the plugins on github pages, but like how would I host them. How would this work.

**Comment by Darth-Ness** [comment]
> > > > For plugins I would recommend not saving them locally. Instead have a list of them stored in local storage or something, then fetch them on startup. Make sure add-on fetching does not block the the app from rendering.
> > > 
> > > 
> > > Saving plugins locally in the Catalyst directory is literally the only way to load plugins without recompiling.
> > 
> > 
> > No, I meant if plugins were downloaded from catalyst.plugins.com (Just an example) everytime someone downloads a plugin, it saves the link to the plugin in local storage. Then on browser start up, using those links. Catalyst reinstalls all of those plugins. Here is an idea of what that would look like in code.
> > ```js
> > if (site == "catalyst.plugins.com) {
> >     //Insert a click listener onto the install button in the webview.
> >     localStorage.setItem('pluginList',  webview.getUrl); 
> >     //Catalyst would probably have to add that to the list by getting the current list then adding the url to it 
> > }
> > ```
> 
> I don't see how this would work. Also I would have to host the plugins on github pages, but like how would I host them. How would this work.

I doubt you could host on GitHub Pages. Replit would probably be better. But basically, you would use a fetch request
to get the addons from wherever you hosted/

**Comment by JaydenDev** [comment]
> > > > > For plugins I would recommend not saving them locally. Instead have a list of them stored in local storage or something, then fetch them on startup. Make sure add-on fetching does not block the the app from rendering.
> > > > 
> > > > 
> > > > Saving plugins locally in the Catalyst directory is literally the only way to load plugins without recompiling.
> > > 
> > > 
> > > No, I meant if plugins were downloaded from catalyst.plugins.com (Just an example) everytime someone downloads a plugin, it saves the link to the plugin in local storage. Then on browser start up, using those links. Catalyst reinstalls all of those plugins. Here is an idea of what that would look like in code.
> > > ```js
> > > if (site == "catalyst.plugins.com) {
> > >     //Insert a click listener onto the install button in the webview.
> > >     localStorage.setItem('pluginList',  webview.getUrl); 
> > >     //Catalyst would probably have to add that to the list by getting the current list then adding the url to it 
> > > }
> > > ```
> > 
> > 
> > I don't see how this would work. Also I would have to host the plugins on github pages, but like how would I host them. How would this work.
> 
> I doubt you could host on GitHub Pages. Replit would probably be better. But basically, you would use a fetch request to get the addons from wherever you hosted/

No matter how, I'd still have to write my own API.
