### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#22]
So i've already tried setting the buttons classes for font awesome icons and ive tried <i> tags with the classes it doesnt work

**Comment by webdev03** [comment]
Which commit in did it work?

**Comment by hello-smile6** [comment]
> Which commit in did it work? I don't see where you import Font Awesome, and also, can't we just download the file of FA instead of using NPM?

```html
<script>
document.write("Which commit in did it work? I don't see where you import Font Awesome, and also, can't we just download the file of FA instead of using NPM?".replace("file","files"));
</script>
```
That explain it?

**Comment by JaydenDev** [comment]
> Which commit in did it work? I don't see where you import Font Awesome, and also, can't we just download the files of FA instead of using NPM?

Your tailwind comment is when it stopped working. Now that I think about it it could of been a directory change

**Comment by JaydenDev** [comment]
I fixed it

**Comment by webdev03** [comment]
I was about to fix it, with Bootstrap icons, it works. But I guess you fixed it?

**Comment by hello-smile6** [comment]
> I was about to fix it, with Bootstrap icons, it works. But I guess you fixed it?

Use your version!!!

**Comment by webdev03** [comment]
Nah, it's fine.

**Comment by hello-smile6** [comment]
> Nah, it's fine.

I want yours!!!
