### ISSUE TITLE
[Bug]: Somehow, this was deployed on Github Pages

### ISSUE THREAD

**Issue by kccuber-scratch** [JaydenDev/Catalyst#229]
### Steps to reproduce the issue?

In the github sidebar on this repo, under "Environments," click "Github-Pages." Click "View Deployment" on the top one.

### What happened?

An error that probably came as a result of it thinking it's actually the browser, and it said that this webpage couldn't be found or something.

### Your environment (if applicable)

Firefox, although I'd assume this error would happen on all browsers.

### Version

N/A

**Comment by JaydenDev** [comment]
This bug is to be reported to the owners/developers of said service. I have checked the settings, and I have not deployed GitHub pages with this repository.
