### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#23]
It's what Catalyst is missing... what it needs to be a huge success...
I don't CARE if you take SOME code from Ninetails just credit em.
Use APIs fine idc just fine a cross platform method of TABS :DDD

**Comment by webdev03** [comment]
Hmm, okay, I can try later...

**Comment by hello-smile6** [comment]
I can give you tabs!!!

**Comment by JaydenDev** [comment]
So umm
```
	file /usr/lib/.build-id/ae/95cfe865250b789af383a3d41377f602ec8ef9 from install of catalyst-1.0.0.dev-1.fc35.x86_64 conflicts with file from package ninetails-2.2.3-1.x86_64
```
this error when installing Catalyst

**Comment by JaydenDev** [comment]
looks like im daily driving Catalyst...

**Comment by webdev03** [comment]
Huh... what? It conflicts with ninetails. Maybe electron?

**Comment by hello-smile6** [comment]
> looks like im daily driving Catalyst...

`sudo rm -rf /usr/lib/.build-id/ae/95cfe865250b789af383a3d41377f602ec8ef9`, I'd say. But do `ls -lA /usr/lib/.build-id/ae/95cfe865250b789af383a3d41377f602ec8ef9` first.

**Comment by JaydenDev** [comment]
FreeCat didn't..

**Comment by hello-smile6** [comment]
> FreeCat didn't..

Strange.

**Comment by JaydenDev** [comment]
also the icons dont work in the built version which is prolly an issue on my end

**Comment by hello-smile6** [comment]
> also the icons dont work in the built version which is prolly an issue on my end

Try enabling nodeIntegration and using `path.join`

**Comment by JaydenDev** [comment]
```
nodeIntegration: true;
```
?

**Comment by hello-smile6** [comment]
> ```
> nodeIntegration: true;
> ```
> 
> ?

add it right below `webviewTag: true`, then you can use Node in webpage JS.

**Comment by JaydenDev** [comment]
ok

**Comment by JaydenDev** [comment]
its not that easy... it didnt work

**Comment by hello-smile6** [comment]
> ok

Make sure you don't use `innerHTML`, `document.write`, or `eval` with it enabled, though.

**Comment by hello-smile6** [comment]
> its not that easy... it didnt work

Could you push to a new branch so I could see?

**Comment by JaydenDev** [comment]
i dont use either, but it didnt work
it built but the icons dont show

no, one branch, main. its all thats needed

**Comment by JaydenDev** [comment]
i pushed my changes

**Comment by hello-smile6** [comment]
> i dont use either, but it didnt work it built but the icons dont show
> 
> no, one branch, main. its all thats needed

Now, use `icon.src=path.join(__dirname,icon_url)` to set the icon URL.

**Comment by JaydenDev** [comment]
umm the font awesome icons don't work like that

**Comment by JaydenDev** [comment]
can you do it all in a PR i have to go..

**Comment by JaydenDev** [comment]
tabs how

**Comment by JaydenDev** [comment]
Tabs should be Catalyst Developer's mind right now. Lets all work on TABS :D

**Comment by webdev03** [comment]
I'll make some Tailwind for you, sorry for making you wait so much, just wait a few minutes.

**Comment by webdev03** [comment]
Okay, well, I did say "I'll make some tailwind for you" but in reality I just modified a bit of Ninetails' awesome CSS, so **please make sure to ask MystPi before using this:**
`index.css`:
```css
@tailwind base;
@tailwind utilities;
@tailwind components;
@layer components {
  .tab {
    @apply flex items-center flex-1 max-w-md p-2 overflow-hidden text-sm text-gray-600 bg-emerald-100 rounded cursor-pointer whitespace-nowrap;
  }
  .active-tab {
    @apply text-white bg-emerald-500 cursor-default font-bold;
  }
}
/* ... other custom styles for migration */
```

For the HTML:
```html
<div class="flex items-center px-4 mt-2">
  <div id="tabs" class="flex items-center flex-1 space-x-2 overflow-auto no-scrollbar">
    <!-- the first tab will be added with some JS -->
  </div>
</div>
```

**Comment by webdev03** [comment]
![image](https://user-images.githubusercontent.com/75148774/146719191-9fb7184a-6eed-4efe-ac2f-e5be08639d95.png)

**Comment by webdev03** [comment]
I can add this all in my fork if this is not a direct copy of MystPi's hard work.

**Comment by webdev03** [comment]
Okay, I'll work on it, since you are busy.

**Comment by webdev03** [comment]
Working on this in #26

**Comment by webdev03** [comment]
> Use APIs fine idc just fine a cross platform method of TABS :DDD

I did have to use `addEventListener` in the webviews, there was no other option for me. Sorry, I know you don't like them, but they are necessary.

**Comment by JaydenDev** [comment]
> > Use APIs fine idc just fine a cross platform method of TABS :DDD
> 
> I did have to use `addEventListener` in the webviews, there was no other option for me. Sorry, I know you don't like them, but they are necessary.

its ok,
the tabs are looking good so far
