### ISSUE TITLE
i seriously need help with Moving forward with Catalyst Native.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#241]
Catalyst Native (4.0) is a highly anticipated project. As of now, I am testing and coding up the GTK version of Catalyst codenamed (Catalyst Native Attempt #2).

**Comment by JaydenDev** [comment]
fr, need help, please...

**Comment by JaydenDev** [comment]
> GTK? So you are moving from Electron to GTK with GTK WebKit or GTK with CEF? Why did you choose GTK? There are many Qt based browsers out there thanks to the QtWebKit/QtWebEngine. I think Qt is much easier to start with than GTK. But, what's the points? There are already so many browsers like that out there. Why did you decided to move away from Electron? If Electron is too limited for you then GTK with GTK WebKit or GTK with CEF or even QtWebKit/QtWebEngine are the same limitations. You should move to a full blown Chromium based browser my friend, if it's the case.

Electron isn't 'native' as well. Electron requires the UI be made of HTML and JavaScript. Said JavaScript cannot access node libraries, meaning I cannot go any forward than a basic UI with tabs and minimal functionality. Also, GTK has already failed me so...

**Comment by 3oheicrw** [comment]
> > GTK? So you are moving from Electron to GTK with GTK WebKit or GTK with CEF? Why did you choose GTK? There are many Qt based browsers out there thanks to the QtWebKit/QtWebEngine. I think Qt is much easier to start with than GTK. But, what's the points? There are already so many browsers like that out there. Why did you decided to move away from Electron? If Electron is too limited for you then GTK with GTK WebKit or GTK with CEF or even QtWebKit/QtWebEngine are the same limitations. You should move to a full blown Chromium based browser my friend, if it's the case.
> 
> Electron isn't 'native' as well. Electron requires the UI be made of HTML and JavaScript. Said JavaScript cannot access node libraries, meaning I cannot go any forward than a basic UI with tabs and minimal functionality. Also, GTK has already failed me so...

Go Qt? QtWebEngine is powerful. But keep in mind, there are a bunch of Qt based browsers out there (otter, dooble, viper, falkon,...) :wink: Another solution is to go full blown Chromium :smile:

**Comment by JaydenDev** [comment]
> > > GTK? So you are moving from Electron to GTK with GTK WebKit or GTK with CEF? Why did you choose GTK? There are many Qt based browsers out there thanks to the QtWebKit/QtWebEngine. I think Qt is much easier to start with than GTK. But, what's the points? There are already so many browsers like that out there. Why did you decided to move away from Electron? If Electron is too limited for you then GTK with GTK WebKit or GTK with CEF or even QtWebKit/QtWebEngine are the same limitations. You should move to a full blown Chromium based browser my friend, if it's the case.
> > 
> > 
> > Electron isn't 'native' as well. Electron requires the UI be made of HTML and JavaScript. Said JavaScript cannot access node libraries, meaning I cannot go any forward than a basic UI with tabs and minimal functionality. Also, GTK has already failed me so...
> 
> Go Qt? QtWebEngine is powerful. But keep in mind, there are a bunch of Qt based browsers out there (otter, dooble, viper, falkon,...) 😉 Another solution is to go full blown Chromium 😄

You probably haven't read up on some details, considering you found this repository through GitHub and not Scratch. But the chromium build tools are a bit of a pain to get working and I haven't been able to. I'll try QT I guess.

**Comment by 3oheicrw** [comment]
Try contributing to or fork one of the already available Qt based browser before starting everything from scratch. There are already too many Qt based browsers. This is everything I could tell you. BTW, if you afraid of C++, you could use Python. Python binding for Qt is excellent and there is PyQtWebEngine too :smile:

**Comment by 3oheicrw** [comment]
Well, your current browser is pretty bad. Why don't you try to improve it but decided to start from scratch? No advertising blocking. Bookmarking doesn't work. You were right. Your browser is nothing but a reskin of Electron, nothing more nothing less. Please have a look at the Min browser, you will see how far people could do with Electron.

**Comment by 3oheicrw** [comment]
@JaydenDev Sorry my friend. I know my words is a bit too harsh. But having to install it to be able to try it (you refused to provide 7z archives), only to find out it's not anything up to my expections. I'm really disappointed. BTW, if you have a preview of Catalyst Native available (of course please provide portable or at least 7z archives), I'm willing to try it and report bugs to you. I think you should make a new repo for Catalyst Native and have this repo archived (since you will no longer develop it anyway). Just my 2 cents.

**Comment by 3oheicrw** [comment]
@JaydenDev I'm really afraid. Are you just too ambitious? You have so many repos and I can only checked a few of them. The fact is most of your projects are failed (you admitted it). Do you think you will success with this Catalyst Native endeavor? It seems your language is JavaScript. Qt and C++ is not anything like JavaScript. Are you serious?

**Comment by 3oheicrw** [comment]
Sorry if I annoyed you. I only interested in your project and wanted to help. Please let me know what I could do to help you and I will do what I can. Looking forward to try Catalyst Native. But now, good bye and good luck to you.
