### ISSUE TITLE
Scratch Log In Bug (From Ninetails code)

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#27]
So the scratch log in bug from ninetails has been brought over. It was fixed in the ninetails update tho. Gotta fix it here.

**Comment by MystPi** [comment]
It's when you have the `x86_64` architecture in a Electron user agent. I've already made an issue on the scratch-www repo (LLK/scratch-www#6395), so they should (hopefully) be aware of it by now.

**Comment by JaydenDev** [comment]
@MystPi so what action should i take to fix it.

**Comment by MystPi** [comment]
Set a custom user agent for now, and when/if the ST fixes the bug you can remove it.

**Comment by JaydenDev** [comment]
So how do I set the user agent and to what

**Comment by webdev03** [comment]
I can!

**Comment by MystPi** [comment]
> So how do I set the user agent and to what

Use the `useragent` attribute on the webview. You can set it to anything you want.

**Comment by webdev03** [comment]
I will fix it, just wait.

**Comment by JaydenDev** [comment]
@webdev03 ok, btw the actual tabs work fine. Just that one bug then it'll be good to go on to the next features.

**Comment by JaydenDev** [comment]
If you do want to improve the tabs go ahead, They are good as they are already though.

**Comment by webdev03** [comment]
I've fixed the bug. I will work on the tabs, after you merge that in. But test my fix first! I haven't tested yet as it is `emer-fix` (emergency fix lol)

**Comment by JaydenDev** [comment]
issue fixed!
