### ISSUE TITLE
[Feature Request]: Make the home screen customizeable.

### ISSUE THREAD

**Issue by UniqueName12345** [JaydenDev/Catalyst#276]
### Is your feature request related to a problem? Please describe.

Not many people would care much about Scratch to make it on the home screen, and even less about Aviate. DDG is a start, but what would be even better would be something where you can add sites to the home screen and change or remove already existing sites. For example, if people feel like using SearX, then let people use SearX. If people want, say, YouTube on their front page, why not let them do that? If they once had DDG as a site on the favourite bar, but now use Bing (why would you), they can click on the pencil icon next to DDG and change the URL to bing and the favicon will also change!

### Describe the solution you would like!

- A plus button next to the already existing bar that opens up a popup with the options:
- - URL [text input] - The url to the site
- A pencil button that only appears when highlighting the site you want to edit, that also opens a popup!
- - URL [text input] - Changing the url of the existing site
- - Duplicate [button] - Duplicates the favourite site one time, and moves it to the right of the previous one. For example, someone wants to use DDG and DDG Lite.
- - Delete [button] - Deletes the favourite site from the list.
- (optional) A way to export favourites into Chrome or (preferably) Firefox [and of course Catalyst itself]

**Comment by JaydenDev** [comment]
This is super complicated to implement... I'll try I guess.

**Comment by UniqueName12345** [comment]
> This is super complicated to implement... I'll try I guess.

Meta Idea: Also make a "Difficulty Scale" form element.

**Comment by JaydenDev** [comment]
As of Catalyst v3.2.0, the home page will no longer receive feature updates and will just be a plain page, as a custom home page can be set by the user, therefore this feature request will be closed.
