### ISSUE TITLE
Add a wiki page on how to create plugins

### ISSUE THREAD

**Issue by redstone-scratch** [JaydenDev/Catalyst#298]
It would make it easier to create plugins if you want us to create plugins :/

**Comment by JaydenDev** [comment]
you probably read the post already

**Comment by UniqueName12345** [comment]
> you probably read the post already

What if you haven't read the post?

> OP

I agree with this! This would be a majorly awesome change, and would be similar to how MDN has pages on how to make a FF browser extension!

**Comment by JaydenDev** [comment]
> > you probably read the post already
> 
> What if you haven't read the post?
> 
> > OP
> 
> I agree with this! This would be a majorly awesome change, and would be similar to how MDN has pages on how to make a FF browser extension!

it's really as simple as creating a folder in the plugins directory, adding a plugin.js, putting code in it, and adding the plugin name to plugins.config.js or whatever its called

**Comment by UniqueName12345** [comment]
> it's really as simple as creating a folder in the plugins directory, adding a plugin.js, putting code in it, and adding the plugin name to plugins.config.js or whatever its called

Compare this with making a FF browser extension where you make a folder, place a manifest.json file directly under the folder in this format:
`{
  "manifest_version": 2,
  "name": "Borderify",
  "version": "1.0",
  "description": "Adds a red border to all webpages matching mozilla.org.",
  "icons": {
    "48": "icons/border-48.png"
  },
  "content_scripts": [
    {
      "matches": ["*://*.mozilla.org/*"],
      "js": ["borderify.js"]
    }
  ]
}
`

Then, make a icons folder and use two icons, one 48x48 and the other 96x96, and then create your js file named after the extension you want it to be called (same as in manifest.json)

**Comment by JaydenDev** [comment]
> > it's really as simple as creating a folder in the plugins directory, adding a plugin.js, putting code in it, and adding the plugin name to plugins.config.js or whatever its called
> 
> Compare this with making a FF browser extension where you make a folder, place a manifest.json file directly under the folder in this format: `{ "manifest_version": 2, "name": "Borderify", "version": "1.0", "description": "Adds a red border to all webpages matching mozilla.org.", "icons": { "48": "icons/border-48.png" }, "content_scripts": [ { "matches": ["*://*.mozilla.org/*"], "js": ["borderify.js"] } ] } `
> 
> Then, make a icons folder and use two icons, one 48x48 and the other 96x96, and then create your js file named after the extension you want it to be called (same as in manifest.json)

for Catalyst its way simpler

**Comment by UniqueName12345** [comment]
> for Catalyst its way simpler

[_[citation needed](something)_]

**Comment by JaydenDev** [comment]
> > for Catalyst its way simpler
> 
> [_[citation needed](something)_]

as simple as creating and editing files

**Comment by UniqueName12345** [comment]
> > > for Catalyst its way simpler
> > 
> > 
> > [_[citation needed](something)_]
> 
> as simple as creating and editing files

And so is making a FF browser extension? I don't understand.

**Comment by JaydenDev** [comment]
> > > > for Catalyst its way simpler
> > > 
> > > 
> > > [_[citation needed](something)_]
> > 
> > 
> > as simple as creating and editing files
> 
> And so is making a FF browser extension? I don't understand.

ive explained the process, its pretty simple

**Comment by UniqueName12345** [comment]
> ive explained the process, its pretty simple

Except I gave steps on how to make a FF extension that are actually as simple as making a catalyst plugin, so what's easier about the than making a browser extension?

**Comment by UniqueName12345** [comment]
And why did you close it as completed if there still isn't a page on how to create plugins, like @redstone-scratch asked in the original post?
