### ISSUE TITLE
[Feature Request]: <Make an Android Linux app, since there's already ones for other distros>

### ISSUE THREAD

**Issue by PPPDUD** [JaydenDev/Catalyst#300]
### Is your feature request related to a problem? Please describe.

The problem is that, sometimes I want to browse the net on my tablet, but Chrome has Family Link restrictions and Samsung Internet is too... awkward.

### Describe the solution you would like!

I would like for there to be an APK version. I expected to see an APK download atleast somewhere, but I couldn't find one.

### Describe alternatives you have considered.

An alternative may be to host a server online at an IP address and then use something like VNC.

**Comment by JaydenDev** [comment]
This already exists, though isn't on the website. You can snag the latest APK from [this link](https://dl.jaydendev.repl.co/CatalystMobile.apk)

**Comment by PPPDUD** [comment]
Thanks

**Comment by PPPDUD** [comment]
How do I tell the search bar I'm ready to go to a URL?
> Thanks
>

**Comment by JaydenDev** [comment]
There's a go button of sorts correct?

**Comment by PPPDUD** [comment]
I can not see any such button.

**Comment by PPPDUD** [comment]
![Screenshot_20221019_162441](https://user-images.githubusercontent.com/107440101/196796629-ee1f19e5-169c-42e9-9e49-fd44ec5558f8.jpg)

**Comment by JaydenDev** [comment]
> ![Screenshot_20221019_162441](https://user-images.githubusercontent.com/107440101/196796629-ee1f19e5-169c-42e9-9e49-fd44ec5558f8.jpg)
I believe that's v1.0, and not a functional version like v1.1 or v1.2, can you figure out what version your running?

**Comment by PPPDUD** [comment]
V1.0. Where do I get the new version?
