### ISSUE TITLE
Searching in the search bar.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#31]
You shouldn't need to copy any more Ninetails code, so please try not to.

Its as simple as,

if no https:// or http://
then search
duck duck go

right...?

**Comment by webdev03** [comment]
I can do that.

**Comment by kccuber-scratch** [comment]
no not DDG, use startpage, google search results but private and better than bings search results (thats what DDG uses right?)

**Comment by JaydenDev** [comment]
ddg is the best, I refuse to use some off-brand crap nobody uses

**Comment by webdev03** [comment]
I have used Duck duck go. I am not changing it right now. Please give me some time to refine the UX for tabs.

**Comment by JaydenDev** [comment]
@webdev03 k

**Comment by webdev03** [comment]
> no not DDG, use startpage, google search results but private and better than bings search results (thats what DDG uses right?)

If they can get "google search results" they connect to google and so you STILL have your search queries sent to google, or am I missing something?

**Comment by JaydenDev** [comment]
arguments slow progress

**Comment by webdev03** [comment]
OK, I am working on favicon.

**Comment by webdev03** [comment]
Resolved by #32
