### ISSUE TITLE
Where is that Tailwind I'm supposed to convert again?

### ISSUE THREAD

**Issue by PPPDUD** [JaydenDev/Catalyst#348]

**Comment by jdev082** [comment]
Take the html classes and convert them. 

PRs MUST BE TESTED BY THE CREATOR

**Comment by PPPDUD** [comment]
Which files?

**Comment by jdev082** [comment]
Please, look around the code before attempting to develop PRs for Catalyst. Also, I advise against the creation of PRs without at least basic knowlege of HTML, CSS, and JS.
