### ISSUE TITLE
Bugs from Tailwind Conversion

### ISSUE THREAD

**Issue by jdev082** [JaydenDev/Catalyst#349]
Catalyst is almost converted, but some things aren't quite right. Even though a change of CSS shouldn't affect the functionality of the UI too badly, there are some bugs to be addressed.

- [x] More menu doesn't open
- [x] Bookmarks area cannot be toggled
- [ ] Tab bar not extending across the entirety of the window
- [ ] utility bar not extending across the entirety of the window

All of these issues apply to the latest source code. Both solutions and outright PRs will be greatly appreciated!

**Comment by michaeleldar** [comment]
I’ll have a look later but I probably won’t be able to help. Idk much JavaScript stuff

**Comment by jdev082** [comment]
> I’ll have a look later but I probably won’t be able to help. Idk much JavaScript stuff

If you don't know at least basic JavaScript it's going to be impossible to develop bug fixes for Catalyst.

**Comment by imdevarsh** [comment]
I think the reason why the more menu does not open is because around https://github.com/jdev082/Catalyst/blob/e5b2b8aac1ac2f801960e9b285f1bcbd81fb5fc8/src/listeners.js#L6 your code tries to use tailwind classes to show/hide the more menu but tailwind isn't there anymore.
You would have to either
(harder) replace it to `element.style.display = 'none'` and change it back when showing, or
(easier) recreate the `.hidden` class

**Comment by michaeleldar** [comment]
> > I’ll have a look later but I probably won’t be able to help. Idk much JavaScript stuff
> 
> If you don't know at least basic JavaScript it's going to be impossible to develop bug fixes for Catalyst.

I do know basic javascript, but it's not my main language at all.

**Comment by jdev082** [comment]
> I think the reason why the more menu does not open is because around https://github.com/jdev082/Catalyst/blob/e5b2b8aac1ac2f801960e9b285f1bcbd81fb5fc8/src/listeners.js#L6 your code tries to use tailwind classes to show/hide the more menu but tailwind isn't there anymore.
> You would have to either
> (harder) replace it to `element.style.display = 'none'` and change it back when showing, or
> (easier) recreate the `.hidden` class

Thing is, I did recreate the hidden class

**Comment by jdev082** [comment]
fixed bookmarks! [435805a](https://github.com/CatalystDevOrg/Catalyst/commit/435805aefd1099c140b785e23056d7e5dabd8db1)

**Comment by jdev082** [comment]
fixed more menu! [04b1714](https://github.com/CatalystDevOrg/Catalyst/commit/04b17142c964e310eb55f81286457b1417399a1a)

**Comment by jdev082** [comment]
Catalyst 4 and 5 won't use Tailwind!
