### ISSUE TITLE
Add spellcheck

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/Catalyst#39]

**Comment by JaydenDev** [comment]
1. No description or context
2. Constantly bothering about the use of and advertisement of your software in which is not needed

Closing, stop it NOW!

**Comment by hello-smile6** [comment]
> 1. No description or context
> 2. Constantly bothering about the use of and advertisement of your software in which is not needed
> 
> Closing, stop it NOW!

Sorry, was just wondering. Also, you could use the Electron built-in one.
