### ISSUE TITLE
WebView doesn't take full available space

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#4]
The webview takes full width but not height.

**Comment by FunctionalMetatable** [comment]
use `100vh` instead of `100%`

**Comment by JaydenDev** [comment]
wha wutt

**Comment by hello-smile6** [comment]
> use `100vh` instead of `100%`

That's what I'm always thinking!!!

**Comment by JaydenDev** [comment]
I've changed all the 100%s, it still doesn't work.

**Comment by hello-smile6** [comment]
> I've changed all the 100%s, it still doesn't work.

What file?

**Comment by JaydenDev** [comment]
Affected Files:
/index.html

Bugs:
Webview not taking entire space

**Comment by hello-smile6** [comment]
> Affected Files: /index.html
> 
> Bugs: Webview not taking entire space

Where's the STYLESHEET?

**Comment by JaydenDev** [comment]
I fixed it
btw materialize is the framework in use
Material UI Design

**Comment by JaydenDev** [comment]
Closing issue, moving development to step to
Forward, Reload, Back buttons

**Comment by JaydenDev** [comment]
#6
