### ISSUE TITLE
[Feature Request]: Add tests so Catalyst won't be a buggy mess

### ISSUE THREAD

**Issue by redstone-dev** [JaydenDev/Catalyst#411]
### Is your feature request related to a problem? Please describe.

As said by Crayon on the Catalyst topic, 3.4.x is a buggy mess.

### Describe the solution you would like!

Adding tests would fix this problem.

### Describe alternatives you have considered.

None.

**Comment by jdev082** [comment]
1. I have no clue how to write tests
2. I have no clue what tests you speak of
3. Tests!?

**Comment by jdev082** [comment]
@redstone-dev If you would like to implement this feature yourself, create a PR and make sure to test it thoroughly.

**Comment by jdev082** [comment]
_how?_
