### ISSUE TITLE
[Bug]: What's new and error pages don't work.

### ISSUE THREAD

**Issue by michaeleldar** [JaydenDev/Catalyst#417]
### Steps to reproduce the issue?

(Probably only a mac-specific issue)
Open catalyst, click the button beside the settings button, then click whatsnew.htm or err.htm.

https://github.com/CatalystDevOrg/Catalyst/assets/66514999/043e1c00-731d-46c1-88dd-daacfd0b387f

### What happened?

I would see what the new features were

### Your environment (if applicable)

OS: macOS 11.7.6
CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Memory: 553.99 MB / 16.00 GB
Shell: 5.8 - /bin/zsh

### Version

3.5.0 (Release version)

**Comment by jdev082** [comment]
You are loading these pages from bookmarks made prior to the release that removed both of those pages. These pages are no longer part of the browser.
