### ISSUE TITLE
Automatic Repository Maintainence

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/Catalyst#46]
### Discussed in https://github.com/JaydenDev/Catalyst/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **JaydenDev** December 22, 2021</sup>
Goals
- Have packages and binaries built automatically whenever a new release is posted in the releases page.
- Automatically add contributors to README.</div>

**Comment by webdev03** [comment]
I'm working on the packages and binaries. Don't worry, I am not copying Ninetails.

**Comment by webdev03** [comment]
https://allcontributors.org/docs/en/bot/installation can help with automatically adding contributors

**Comment by hello-smile6** [comment]
> https://allcontributors.org/docs/en/bot/installation can help with automatically adding contributors

Nice! Could you add that to my sp project, by chance?

**Comment by JaydenDev** [comment]
You can't create a tag without making a release.

**Comment by JaydenDev** [comment]
@webdev03

**Comment by webdev03** [comment]
You can!

**Comment by hello-smile6** [comment]
> You can't create a tag without making a release.

You sure?

**Comment by JaydenDev** [comment]
@webdev03 i got it to work but your gh action failed

**Comment by webdev03** [comment]
Hmm, that's weird.

**Comment by JaydenDev** [comment]
That's not the problem, the problem is that you uploaded a broken PR. That's a problem.

**Comment by webdev03** [comment]
I got it! I know why!
Merge it again.

**Comment by hello-smile6** [comment]
> I got it! I know why! Merge it again. For some reason, my formatting broke.

What, did you use Prettier?

**Comment by JaydenDev** [comment]
@webdev03 EXACTLY

why did you use prettier
that is strictly banned

**Comment by webdev03** [comment]
No, I didn't. Actually, it was a typo.

**Comment by hello-smile6** [comment]
> No, I didn't. Actually, it was a typo.

What word did you misspell? What was the correct spelling?

**Comment by webdev03** [comment]
I forgot to press tab once 🤣 sorry

**Comment by webdev03** [comment]
https://github.com/webdev03/Catalyst/runs/4611996477?check_suite_focus=true see it works!

**Comment by VelocityDesign** [comment]
It doesn't look like that worked @webdev03. The publish script is missing.

**Comment by webdev03** [comment]
Yes, just add the package script as
`"publish": "electron-forge publish",`
I didn't want to add it as I was testing it.

**Comment by JaydenDev** [comment]
@webdev03 it failed again btw

**Comment by webdev03** [comment]
#52

**Comment by VelocityDesign** [comment]
Off-topic:
@JaydenDev See #48

**Comment by hello-smile6** [comment]
> Off-topic: @JaydenDev See #48

They already knew. https://github.com/JaydenDev/Catalyst/watchers

**Comment by JaydenDev** [comment]
it should be built server side, not on my machine.

**Comment by hello-smile6** [comment]
> it should be built server side, not on my machine.

Then run whatever you'd run locally using GitHub Actions.

**Comment by JaydenDev** [comment]
@webdev03 that's what you were supposed to make but didnt when i said i wanted automation

**Comment by JaydenDev** [comment]
@webdev03 this is supposed to be running server side
An unhandled rejection has occurred inside Forge:
Error: Please set GITHUB_TOKEN in your environment to access these features
    at new GitHub (/home/jmwills/GitHub/Catalyst/node_modules/@electron-forge/publisher-github/src/util/github.ts:36:13)
    at PublisherGithub.publish (/home/jmwills/GitHub/Catalyst/node_modules/@electron-forge/publisher-github/src/PublisherGithub.ts:46:20)
    at publish (/home/jmwills/GitHub/Catalyst/node_modules/@electron-forge/core/src/api/publish.ts:180:21)
    at /home/jmwills/GitHub/Catalyst/node_modules/@electron-forge/cli/src/electron-forge-publish.ts:36:3

Electron Forge was terminated. Location:
{}

**Comment by JaydenDev** [comment]
The way Ninetails has it.

**Comment by webdev03** [comment]
Yes, you need to make a tag. `npm run publish` is run on Github actions. Make a tag.

**Comment by JaydenDev** [comment]
> Yes, you need to make a tag. `npm run publish` is run on Github actions. Make a tag.

That's what I did but it's not that easy
It requires to much setup more than just building myself.

It's not gonna work
All I want is for me to make a released and have packages uploaded automatically to the release and it all to be server side

**Comment by hello-smile6** [comment]
> > Yes, you need to make a tag. `npm run publish` is run on Github actions. Make a tag.
> 
> That's what I did but it's not that easy It requires to much setup more than just building myself.
> 
> It's not gonna work All I want is for me to make a released and have packages uploaded automatically to the release and it all to be server side

I'll do it

**Comment by webdev03** [comment]
Just run
`npm version 0.4.0` or what version you want
then `git push --follow-tags`
then it will start!!!

**Comment by JaydenDev** [comment]
> Just run
> `npm version 0.4.0` or what version you want
> then `git push --follow-tags`
> then it will start!!!
> It's that simple. I didn't want to copy Ninetails.

Not simple it requires getting and setting up environment variables

**Comment by hello-smile6** [comment]
> > Just run
> > `npm version 0.4.0` or what version you want
> > then `git push --follow-tags`
> > then it will start!!!
> > It's that simple. I didn't want to copy Ninetails.
> 
> Not simple it requires getting and setting up environment variables

I'll do it...

**Comment by JaydenDev** [comment]
> > Just run
> > `npm version 0.4.0` or what version you want
> > then `git push --follow-tags`
> > then it will start!!!
> > It's that simple. I didn't want to copy Ninetails.
> 
> Not simple it requires getting and setting up environment variables

That are hard to get
I want it completely automatic. Streamline it

**Comment by hello-smile6** [comment]
> > > Just run
> > > `npm version 0.4.0` or what version you want
> > > then `git push --follow-tags`
> > > then it will start!!!
> > > It's that simple. I didn't want to copy Ninetails.
> > 
> > 
> > Not simple it requires getting and setting up environment variables
> 
> That are hard to get I want it completely automatic. Streamline it

I'M GOING!!!

**Comment by JaydenDev** [comment]
> > > > Just run
> > > > `npm version 0.4.0` or what version you want
> > > > then `git push --follow-tags`
> > > > then it will start!!!
> > > > It's that simple. I didn't want to copy Ninetails.
> > > 
> > > 
> > > Not simple it requires getting and setting up environment variables
> > 
> > That are hard to get I want it completely automatic. Streamline it
> 
> I'M GOING!!!

You won't not fail though, you break things so much

**Comment by hello-smile6** [comment]
> > > > > Just run
> > > > > `npm version 0.4.0` or what version you want
> > > > > then `git push --follow-tags`
> > > > > then it will start!!!
> > > > > It's that simple. I didn't want to copy Ninetails.
> > > > 
> > > > 
> > > > Not simple it requires getting and setting up environment variables
> > > 
> > > 
> > > That are hard to get I want it completely automatic. Streamline it
> > 
> > 
> > I'M GOING!!!
> 
> You won't not fail though, you break things so much

I'm not going to fail. I'll test it on my fork. If it works, I'll demonstrate it.

**Comment by VelocityDesign** [comment]
Or we could just get permission from Ninetails to use their build thing from GH Actions.

**Comment by JaydenDev** [comment]
> Or we could just get permission from Ninetails to use their build thing from GH Actions.

We already take enough code

**Comment by VelocityDesign** [comment]
*shrugs* your loss...

**Comment by hello-smile6** [comment]
> _shrugs_ your loss...

I'm over this drama. I'm making my own Electron browser that actually _works_. Want to help me?

**Comment by webdev03** [comment]
> > Just run
> > `npm version 0.4.0` or what version you want
> > then `git push --follow-tags`
> > then it will start!!!
> > It's that simple. I didn't want to copy Ninetails.
> 
> Not simple it requires getting and setting up environment variables

That is done on github actions. Already done, secrets.GITHUB_TOKEN is automatically provided.

**Comment by hello-smile6** [comment]
> > > Just run
> > > `npm version 0.4.0` or what version you want
> > > then `git push --follow-tags`
> > > then it will start!!!
> > > It's that simple. I didn't want to copy Ninetails.
> > 
> > 
> > Not simple it requires getting and setting up environment variables
> 
> That is done on github actions. Already done, secrets.GITHUB_TOKEN is automatically provided.

Their loss.

**Comment by JaydenDev** [comment]
@webdev03 alright

**Comment by VelocityDesign** [comment]
@JaydenDev Just listen to what webdev03 is saying. It will take 10x less time to just do that.

**Comment by JaydenDev** [comment]
@VelocityDesign Its hard to comprehend what the heck anything he makes does

**Comment by webdev03** [comment]
Okay, I will write documentation soon.

**Comment by VelocityDesign** [comment]
Maybe make an org and give him access to secrets? Then he could do config himself.

**Comment by JaydenDev** [comment]
@VelocityDesign WOAH WOAH WOAH, I know what happened last time I gave someone else write access.
@hello-smile6 broke everything that way

**Comment by VelocityDesign** [comment]
> @VelocityDesign WOAH WOAH WOAH, I know what happened last time I gave someone else write access. @hello-smile6 broke everything that way

Only to the secrets. After that, you could remove it. There's a line between insecure and paranoid that you need to find.

**Comment by webdev03** [comment]
Secrets, I thought github actions automatically defines `secrets.GITHUB_TOKEN`?

**Comment by JaydenDev** [comment]
It is getting pushed, check tags. I deleted em tho.

**Comment by JaydenDev** [comment]
> > @VelocityDesign WOAH WOAH WOAH, I know what happened last time I gave someone else write access. @hello-smile6 broke everything that way
> 
> Only to the secrets. After that, you could remove it. There's a line between insecure and paranoid that you need to find.

Mistakes repeat unless prevented.

**Comment by webdev03** [comment]
https://github.com/JaydenDev/Catalyst/runs/4612290380?check_suite_focus=true Check this out.

**Comment by JaydenDev** [comment]
@webdev03 nice now tell me how you did it

**Comment by webdev03** [comment]
It works. You just need to go to the releases page, edit the things, and release it I guess.
My github action did it.

**Comment by JaydenDev** [comment]
@webdev03 perfection, now time for goal 2. Contributors being added to README.md automatically.

**Comment by webdev03** [comment]
Wait, since you deleted the tag, you couldn't release it... and check the release, the assets aren't there since you released it, not my script.

**Comment by webdev03** [comment]
https://github.com/JaydenDev/Catalyst/issues/46#issuecomment-999882986 can be for auto adding contributors, just open an issue for this.

**Comment by JaydenDev** [comment]
it makes RPM builds right?
im on fedora

**Comment by VelocityDesign** [comment]
Flatpak > RPM. 
I'm on Fedora Silverblue btw

**Comment by JaydenDev** [comment]
@VelocityDesign I don't need to put any more tasks on these people.

**Comment by webdev03** [comment]
Which people?

**Comment by VelocityDesign** [comment]
> @VelocityDesign I don't need to put any more tasks on these people.

I was working on flatpak actually...

**Comment by JaydenDev** [comment]
> > @VelocityDesign I don't need to put any more tasks on these people.
> 
> I was working on flatpak actually...

oh... but the question is... why?

**Comment by JaydenDev** [comment]
> Which people?

when there is something I can't do which is a lot of things i have to wait for someone else to do it :(

**Comment by VelocityDesign** [comment]
> > > @VelocityDesign I don't need to put any more tasks on these people.
> > 
> > 
> > I was working on flatpak actually...
> 
> oh... but the question is... why?

It's universal and preferred by the fedora project.

**Comment by webdev03** [comment]
By the way, did you see? Your release has all of the exe, zip, and a "nupkg"?

**Comment by JaydenDev** [comment]
@webdev03 So, the building thing worked! It made a release and added the binaries all i had to do was finish the release and publish it.

**Comment by JaydenDev** [comment]
> By the way, did you see? Your release has all of the exe, zip, and a "nupkg"?

yeah

**Comment by webdev03** [comment]
@github-actions thanks!

**Comment by JaydenDev** [comment]
@hello-smile6 sorry dud

**Comment by VelocityDesign** [comment]
> @webdev03 So, the building thing worked! It made a release and added the binaries all i had to do was finish the release and publish it.

Awesome!

**Comment by VelocityDesign** [comment]
I can't get it to build my system for some reason.

**Comment by hello-smile6** [comment]
> @hello-smile6 sorry dud

What?

**Comment by JaydenDev** [comment]
> > @hello-smile6 sorry dud
> 
> What?

Sorry for being mean

**Comment by JaydenDev** [comment]
> I can't get it to build my system for some reason.

But why flatpaks they take more space than regular packages

**Comment by VelocityDesign** [comment]
> > I can't get it to build my system for some reason.
> 
> But why flatpaks they take more space than regular packages
Because they're better than snaps.

**Comment by JaydenDev** [comment]
> > > I can't get it to build my system for some reason.
> > 
> > 
> > But why flatpaks they take more space than regular packages
> 
> Because they're better than snaps.

why use snaps or flatpaks

**Comment by VelocityDesign** [comment]
> > > > I can't get it to build my system for some reason.
> > > 
> > > 
> > > But why flatpaks they take more space than regular packages
> > 
> > 
> > Because they're better than snaps.
> 
> why use snaps or flatpaks

Because they're secure
(And because I have to on Silverblue lol)

**Comment by JaydenDev** [comment]
> > > > > I can't get it to build my system for some reason.
> > > > 
> > > > 
> > > > But why flatpaks they take more space than regular packages
> > > 
> > > 
> > > Because they're better than snaps.
> > 
> > 
> > why use snaps or flatpaks
> 
> Because they're secure (And because I have to on Silverblue lol)

Why are you using Silverblue

**Comment by VelocityDesign** [comment]
![Screenshot from 2021-12-22 17-04-22](https://user-images.githubusercontent.com/24457862/147164759-c93ea087-2f03-46ba-a2d2-89d0b8636c15.png)
Umm I'm not sure this is working...

**Comment by hello-smile6** [comment]
> ![Screenshot from 2021-12-22 17-04-22](https://user-images.githubusercontent.com/24457862/147164759-c93ea087-2f03-46ba-a2d2-89d0b8636c15.png) Umm I'm not sure this is working...

```bash
npm run dev
```

**Comment by hello-smile6** [comment]
Nice OS.

**Comment by JaydenDev** [comment]
You have to run 'npm run dev' to have the CSS done, then build it

**Comment by VelocityDesign** [comment]
This is the released RPM.

> Nice OS.

And thanks. It's GNOME + extensions on fedora silverblue.

**Comment by hello-smile6** [comment]
> This is the released RPM.
> 
> > Nice OS.
> 
> And thanks. It's GNOME + extensions on fedora silverblue.

Could I have your .iso and an x64 standalone QEMU binary that could run it?

**Comment by JaydenDev** [comment]
@webdev03 we have quite the problem

since gh actions is building from repository its not building the tailwind css first

**Comment by VelocityDesign** [comment]
> 

I don't think I can package my system with that...

**Comment by JaydenDev** [comment]
@VelocityDesign gh actions stuff gotta be fixed then a succesful complete RPM build then you can do ur thing

**Comment by VelocityDesign** [comment]
> @VelocityDesign gh actions stuff gotta be fixed then a succesful complete RPM build then you can do ur thing

Okay. Let me know once that's ready.

**Comment by webdev03** [comment]
> @webdev03 we have quite the problem
> 
> since gh actions is building from repository its not building the tailwind css first

Oh right, I will make a PR to change that. Oops!

**Comment by webdev03** [comment]
Fixed, I made #58

**Comment by VelocityDesign** [comment]
Okay, but an action doesn't seem to be running.

**Comment by webdev03** [comment]
Which one?

**Comment by VelocityDesign** [comment]
The one to build it

**Comment by hello-smile6** [comment]
> The one to build it

Just letting you know, #59

**Comment by webdev03** [comment]
By the way, the reason why it won't build, you need to make a new tag for the action to run :smile:

**Comment by hello-smile6** [comment]
> By the way, the reason why it won't build, you need to make a new tag for the action to run 😄

👍

**Comment by JaydenDev** [comment]
this is all done now

**Comment by VelocityDesign** [comment]
Is it? I don't see anything.

**Comment by hello-smile6** [comment]
> Is it? I don't see anything.

Huh.

**Comment by webdev03** [comment]
Add all-contributors!

**Comment by webdev03** [comment]
@JaydenDev when you come back, open this up.
> Automatically add contributors to README.
