### ISSUE TITLE
[Bug]: Custom titlebar breaks the entire application

### ISSUE THREAD

**Issue by dumorando** [JaydenDev/Catalyst#478]
### Steps to reproduce the issue?

use the program

### What happened?

crashes and i have to force quit it

i expected to be able to use the browser

Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_cataly3GCyyO/resources/app.asar/node_modules/custom-electron-titlebar/main/attach-titlebar-to-window.js:23:31)
    at BrowserWindow.emit (node:events:525:35)

### Your environment (if applicable)

ubuntu 22.04 with the deb file and i tried appimage same thing happened

### Version

3.5.4

**Comment by jdev082** [comment]
Does switching to the Flatpak version of Catalyst solve this problem?

**Comment by dumorando** [comment]
nope

**Comment by jdev082** [comment]
> nope

I can't reproduce the bug and the containerized version doesn't work there isn't much that can be done other than downgrading to `v3.4.x`. You'll miss out on a few features. I have never experienced this bug and it's rather mysterious.

**Comment by jdev082** [comment]
If you have some programming experience you can create a custom build without the new titlebar. This is what's causing the problem. Then you can utilize new releases.

**Comment by dumorando** [comment]
ok

**Comment by jdev082** [comment]
This is a known issue with the library used for the custom titlebar. When it's fixed, I'll release a bug fix with the update.

You can read more about it here: https://github.com/AlexTorresDev/custom-electron-titlebar/issues/240

**Comment by jdev082** [comment]
Not the first issue I've had with this library. Might remove it in the next release:
https://github.com/orgs/CatalystDevOrg/discussions/479

**Comment by jdev082** [comment]
I was able to reproduce the bug on Fedora GNOME so maybe it's a problem with GNOME. Are you using the GNOME version of Ubuntu (The default flavor of ubuntu from ubuntu.com)

**Comment by dumorando** [comment]
ye

**Comment by jdev082** [comment]
This problem will be fixed in Catalyst v3.6.0 (the beta containing the fix will be releasing shortly)

problem is the build system is broken

**Comment by dumorando** [comment]
i moved to plasma and it still doesnt work for me

**Comment by jdev082** [comment]
> i moved to plasma and it still doesnt work for me

The custom titlebar was completely dropped in v3.6.0. Try updating to the latest release.

**Comment by dumorando** [comment]
yep it works now
