### ISSUE TITLE
Update notifier

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#54]
I can make this if you would like. I can make it a native dialog box.

**Comment by JaydenDev** [comment]
I can do the front end and styli-- Nevermind, your HTML is complicated.

**Comment by webdev03** [comment]
My html is complicated? We could use Vue or something.

**Comment by webdev03** [comment]
Would adding `cross-fetch` to the browser be fine?

**Comment by JaydenDev** [comment]
idk what that is

also, ya think a browser needs to be done in vue what the... I'm better at HTML and CSS than a language I don't even known existed

**Comment by webdev03** [comment]
Okay, `cross-fetch` is an npm library, I will open up a native dialog box (like an info popup on windows, or a rounded thing on mac) if there is an update.

**Comment by JaydenDev** [comment]
@webdev03
native dialog boxes... yes

but... You have contributed more code than I, the repo owner, have contributed. I think it being my repo is slowing development down.

**Comment by webdev03** [comment]
I have less commits, though. I tend to make mega-commits instead of short ones.

**Comment by JaydenDev** [comment]
> I have less commits, though. I tend to make mega-commits instead of short ones.

how do I make this repository less of a war ground?

**Comment by webdev03** [comment]
War ground? Anyways, I will start work on the updater.

**Comment by webdev03** [comment]
Close this issue, my PR #57
