### ISSUE TITLE
what browser this based on?

### ISSUE THREAD

**Issue by Talion117** [JaydenDev/Catalyst#540]
what is this one based on, google chrome or firefox? does this support chrome extensions an firefox too?

**Comment by jdev082** [comment]
Chromium. There's no extension support yet. You can request features. The next release is in development, so now is the time.

**Comment by Talion117** [comment]
cool, sweet

**Comment by Talion117** [comment]
can you add more options for sidebar to move to the left?

im trying to also change th default search engine?

**Comment by jdev082** [comment]
> can you add more options for sidebar to move to the left?
> 
> im trying to also change th default search engine?

Yes. The search engine can be changed in preferences.

**Comment by jdev082** [comment]
Go ahead and make a feature request for the sidebar options

**Comment by Talion117** [comment]
> > can you add more options for sidebar to move to the left?
> > im trying to also change th default search engine?
> 
> Yes. The search engine can be changed in preferences.

oh really, i tried switching to brave. it didnt changed to it.

**Comment by jdev082** [comment]
> oh really, i tried switching to brave. it didnt changed to it.

Try restarting Catalyst. If that doesn't work, create a bug report and when I have time I'll fix it and release an update.

**Comment by Talion117** [comment]
looks like my favorite web browser yandex been crashing my computer lately. 

is it possible to import bookmarks an passwords from yandex to catalyst?

**Comment by jdev082** [comment]
> looks like my favorite web browser yandex been crashing my computer lately. 
> 
> is it possible to import bookmarks an passwords from yandex to catalyst?

Not yet, but you can open a feature request. Also, a forum is available at https://github.com/orgs/CatalystDevOrg/discussions

**Comment by jdev082** [comment]
@Talion117 When you export bookmarks from Yandex, what type of file is it? (Look at the ending)

**Comment by Talion117** [comment]
> @Talion117 When you export bookmarks from Yandex, what type of file is it? (Look at the ending)

its a html file.
