### ISSUE TITLE
[Feature Request]: Add option to move sidebar to the left

### ISSUE THREAD

**Issue by Talion117** [JaydenDev/Catalyst#542]
### Is your feature request related to a problem? Please describe.

can you add a option to switch left sidebar? 

### Describe the solution you would like!

i know it may stay on the rightsidebar, but hoping to have a way to switch it to the left. 

hopefully that made sense.

**Comment by jdev082** [comment]
If all goes well this feature will be available in the next beta (tomorrow).

**Comment by jdev082** [comment]
This feature has been added in [v3.9.6 Beta 2](https://github.com/CatalystDevOrg/Catalyst/releases/tag/v3.9.6-beta.2).
