### ISSUE TITLE
[Bug]: the sidebar is not changing search engines even after selecting brave

### ISSUE THREAD

**Issue by Talion117** [JaydenDev/Catalyst#544]
### Steps to reproduce the issue?

you go to prefences, go to advance an select search engine an choose brave.

### What happened?

when changing from google to brave, nothing happens when you select the sidebar.

### Version

v3.9.4

**Comment by jdev082** [comment]
# Short Version
The default URL for the sidebar is currently hard-coded I might make the default URL be the search engine selected in preferences in the next update.
# Long Version
During development google.com was the hard-coded default URL for the sidebar. The sidebar implementation was half-baked so it was later marked as experimental. I haven't coded the sidebar to follow the set search engine as I originally thought of a sidebar as a thing for multi-tasking (was originally gonna be side-by-side tabs). Hence why the only option for the sidebar available at the moment is to open new windows in in it.

**Comment by Talion117** [comment]
> or

that makes sense. since its hard coded based.

**Comment by jdev082** [comment]
As of `v3.9.6-beta.3` (releasing soon) the sidebar now defaults to the selected search engine.
