### ISSUE TITLE
Why can't I comment on some issues???

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/Catalyst#55]
I'm confused.

**Comment by JaydenDev** [comment]
Idk bug

**Comment by hello-smile6** [comment]
> Idk bug

Could you check access? I can't comment on https://github.com/JaydenDev/Catalyst/pull/53 , for example.

**Comment by JaydenDev** [comment]
> > Idk bug
> 
> Could you check access? I can't comment on #53 , for example.

thats... a PR.

**Comment by hello-smile6** [comment]
> > > Idk bug
> > 
> > 
> > Could you check access? I can't comment on #53 , for example.
> 
> thats... a PR.

Well, I can't comment on it for some reason.

**Comment by JaydenDev** [comment]
@hello-smile6 its cuz its closed, you aren't supposed to comment on closed PRs.

**Comment by hello-smile6** [comment]
> @hello-smile6 its cuz its closed, you aren't supposed to comment on closed PRs.

Did you do something to it?

**Comment by hello-smile6** [comment]
@webdev03 I can't comment on anything that you create or use reactions with any of your comments.
