### ISSUE TITLE
> I have less commits, though. I tend to make mega-commits instead of short ones.

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/Catalyst#56]
> I have less commits, though. I tend to make mega-commits instead of short ones.

how do I make this repository less of a war ground?

_Originally posted by @JaydenDev in https://github.com/JaydenDev/Catalyst/issues/54#issuecomment-999930556_

Maybe make it a github org and give everyone access based on how much you trust them. For example, those you trust to tag issues and pull requests could have the ability to do so. (I can't comment on the original issue, see #55 )

**Comment by hello-smile6** [comment]
@VelocityDesign @JaydenDev @webdev03 Just letting you know about this

**Comment by JaydenDev** [comment]
@hello-smile6 after you broke and made a mess, no.

**Comment by JaydenDev** [comment]
this belongs in discussions

**Comment by hello-smile6** [comment]
> @hello-smile6 after you broke and made a mess, no.

Obviously, I would **not** have write access.
