### ISSUE TITLE
A better system...

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#59]
Gotta make the repository better for the community

Suggest anything OTHER than a gh org. I'm NOT giving anyone write permissions, GitHub lacks permission customization and only gives the collaborators page which, @hello-smile6 proved that's a bad idea.

**Comment by webdev03** [comment]
Which collaborators page? Sorry I forgot.

**Comment by JaydenDev** [comment]
Ok, everyone. Step 1: stop arguing.

**Comment by hello-smile6** [comment]
> Gotta make the repository better for the community
> 
> Suggest anything OTHER than a gh org. I'm NOT giving anyone write permissions, GitHub lacks permission customization and only gives the collaborators page which, @hello-smile6 proved that's a bad idea.

It gives you the ability to allow "triage" access for orgs.

**Comment by hello-smile6** [comment]
> Ok, everyone. Step 1: stop arguing.

That can be arranged.

**Comment by hello-smile6** [comment]
<details>
<summary>Off-topic</summary>
llk/scratch-www#6403 just showed up!
</details>

**Comment by hello-smile6** [comment]
@JaydenDev What else?

**Comment by webdev03** [comment]
Also, I don't understand the current versioning system... why not normal `0.0.1` or `1.0.0` like that?

**Comment by JaydenDev** [comment]
> Also, I don't understand the current versioning system... why not normal `0.0.1` or `1.0.0` like that?

Because dev constant and beta builds use Windows like builds strings

**Comment by JaydenDev** [comment]
Have since moved to hundred strings

**Comment by JaydenDev** [comment]
I got the version system from both Windows and Ubuntu, see their releases

**Comment by JaydenDev** [comment]
Classic version systems are old and unorganized

**Comment by JaydenDev** [comment]
I prefer builds to be year month day number

**Comment by webdev03** [comment]
Hmm, okay, as long as you find a way to not break the auto updator.

**Comment by JaydenDev** [comment]
Why prefer 1.0 over 21.12

**Comment by webdev03** [comment]
Oh, I thought the versions were `21.12.10104.284` or something.

**Comment by JaydenDev** [comment]
@webdev03 
21.12 is a stable release
21.12.100 would be beta/pre-release
21.12.2202 would be dev (year.month.day,number)

**Comment by webdev03** [comment]
Oh, okay! Just don't add anything that isn't either a number or `.` in your tag name. It automatically removes the first letter, so you can add a v at the start of every one of your tag names.

**Comment by JaydenDev** [comment]
@webdev03 whats the command to make gh do tag creation in the push command

**Comment by webdev03** [comment]
You do `git push --follow-tags` once you made a tag (`npm version` commands automatically make tags too)

**Comment by JaydenDev** [comment]
#70
