### ISSUE TITLE
Forward, Back, Reload.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#6]
I handled the UI and buttons in index.html
*couldn't get the fontawesome icons working though*

The functions just have to be handled

Remember all javascript goes in /src/

**Comment by JaydenDev** [comment]
I got reload done

**Comment by JaydenDev** [comment]
alright now back and forward are both done

**Comment by VelocityDesign** [comment]
Yay!

**Comment by JaydenDev** [comment]
@VelocityDesign dont get too happy yet
I still can't get font awesome icons to work

**Comment by JaydenDev** [comment]
#9

**Comment by hello-smile6** [comment]
> I handled the UI and buttons in index.html _couldn't get the fontawesome icons working though_
> 
> The functions just have to be handled
> 
> Remember all javascript goes in /src/

Where does the rest go? `/dev/fb0`?
