### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#60]
Goals
- Remove both scrollbars for a clean interface
- Overall UI Cleanup, to make it fresh. 
- Make it completely usable.

**Comment by webdev03** [comment]
Which "both scrollbars" (context: I use a mac)? Also what is unusable?

**Comment by JaydenDev** [comment]
@webdev03 
the horizontal and vertical scroll bars ruin aesthetic.

**Comment by webdev03** [comment]
Can you send a screenshot? Only then I can fix it.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147166780-eac1a04f-9033-47de-924d-551f0c856fbe.png)
scroll bars are quite ugly

**Comment by webdev03** [comment]
Ohhh... I see! I'll fix it. Just wait a minute!

**Comment by hello-smile6** [comment]
@webdev03 Your account's broken. Attempting to follow you or doing anything to do with you results in a <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422">`422`</a> error.

**Comment by webdev03** [comment]
My account isn't broken.

**Comment by VelocityDesign** [comment]
@JaydenDev Make the release public?

**Comment by JaydenDev** [comment]
@VelocityDesign wdym?

**Comment by JaydenDev** [comment]
https://github.com/JaydenDev/Catalyst/releases/tag/v21.12.104
this build now includes the styling.

**Comment by VelocityDesign** [comment]
I will be doing a UI restyle to match the branding. I'll probably go with a blur style similar to https://explorer.helium.com/

**Comment by hello-smile6** [comment]
> I will be doing a UI restyle to match the branding. I'll probably go with a blur style similar to https://explorer.helium.com/

Could I have my logo please?

**Comment by JaydenDev** [comment]
> I will be doing a UI restyle to match the branding. I'll probably go with a blur style similar to https://explorer.helium.com/
alright, make sure to use tailwind! it'll make it easier

**Comment by JaydenDev** [comment]
> I will be doing a UI restyle to match the branding. I'll probably go with a blur style similar to https://explorer.helium.com/

make sure to use tailwind

**Comment by webdev03** [comment]
yes tailwind!!

**Comment by VelocityDesign** [comment]
> Goals
> ...
> - Make it completely usable.

Totally read that as unstable lol

**Comment by hello-smile6** [comment]
Did @webdev03 block me?

**Comment by JaydenDev** [comment]
@webdev03 your fix doesnt work

**Comment by webdev03** [comment]
Oh, okay, I'm confused why the scrollbars are there.

**Comment by hello-smile6** [comment]
> Oh, okay, I'm confused why the scrollbars are there.

Did you block me?

**Comment by JaydenDev** [comment]
> Oh, okay, I'm confused why the scrollbars are there.

well its because you used class="" instead of style="" maybe?

**Comment by webdev03** [comment]
`style` is for normal CSS, `class` is for tailwind.

**Comment by webdev03** [comment]
Wait, really? 🥳

**Comment by webdev03** [comment]
The thing is now, the fullscreen mode kind of broke, but it's fine, make sure webview scrolling works, if it doesn't I will bring out a patch.

**Comment by JaydenDev** [comment]
Catalyst is now out of dev, now in beta. Let's get goin so the pre-release can release next week.

**Comment by JaydenDev** [comment]
#70
