### ISSUE TITLE
all-contributors

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#65]
Here is the way to add it https://allcontributors.org/docs/en/bot/installation

**Comment by JaydenDev** [comment]
Yeah I don't think giving me a link helps
Copying and pasting code does tho so

**Comment by webdev03** [comment]
But you can't copy paste code. You have to get the github app. https://github.com/apps/allcontributors/installations/new add it to the Catalyst repo

**Comment by webdev03** [comment]
@JaydenDev https://github.com/apps/allcontributors/installations/new and install it!!

**Comment by JaydenDev** [comment]
not right nowwww

**Comment by webdev03** [comment]
ok...

**Comment by webdev03** [comment]
What is @The-Catalyst-Browser-Project ?

**Comment by JaydenDev** [comment]
@webdev03 it was my failed attempt to get it done, I've rethought it and im not doing it... too risky to give right acccess.

**Comment by JaydenDev** [comment]
#70

**Comment by webdev03** [comment]
When did I need to have write access? I thought, we can also make a repository for the website, and it will be more organised, then you can set up your projects and stuff.

**Comment by webdev03** [comment]
> @webdev03 it was my failed attempt to get it done, I've rethought it and im not doing it... too risky to give right acccess.

What about all-contributors ? Will you add it or have you already?

**Comment by webdev03** [comment]
Should this be reopened @JaydenDev ?

**Comment by webdev03** [comment]
I can demo it on the website first.

**Comment by webdev03** [comment]
@JaydenDev https://github.com/webdev03/scratchinfo I added all contributors to Scratchinfo. See?

**Comment by hello-smile6** [comment]
> @JaydenDev https://github.com/webdev03/scratchinfo I added all contributors to Scratchinfo. See?

Want @Electron-Web-Browser ? I'll give it to you

**Comment by webdev03** [comment]
@JaydenDev want to do it?

**Comment by JaydenDev** [comment]
@webdev03 you shouldn't keep spamming this issue even after I close the original.

**Comment by webdev03** [comment]
I thought you had said
> @webdev03 it was my failed attempt to get it done, I've rethought it and im not doing it... too risky to give right acccess.
