### ISSUE TITLE
1.0, Features and Progress

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#70]
21.1 release will be on January 1st,
First Pre-Release next week

Let's work on stuff, and prepare for pre-release.

**Comment by JaydenDev** [comment]
@webdev03 Can you make this all have one background color. I like the gray color more than the black.
![image](https://user-images.githubusercontent.com/92550746/147288374-adbb41e5-abde-43eb-823b-240f47c63c23.png)

**Comment by JaydenDev** [comment]
@webdev03 ignore, I've already changed it.

**Comment by JaydenDev** [comment]
Ok, so I think its better if the space between the tabs and the action bar should be decreased.

**Comment by webdev03** [comment]
I can try.

**Comment by JaydenDev** [comment]
@webdev03 for the search suggestions can you make the top have square corners and the bottom rounded

**Comment by webdev03** [comment]
OK!

**Comment by JaydenDev** [comment]
@webdev03 why caps?

**Comment by webdev03** [comment]
OK = Okay
I will stop now

**Comment by JaydenDev** [comment]
@webdev03 are you able to decrease the space between the bar and the tabs?

**Comment by webdev03** [comment]
Hmm, ok

**Comment by webdev03** [comment]
You mean the search bar and the tabs?

**Comment by JaydenDev** [comment]
> You mean the search bar and the tabs?

yes, less space between them. Make it more like the space between the two in FF

**Comment by webdev03** [comment]
OK

**Comment by webdev03** [comment]
<img width="1023" alt="Screen Shot 2021-12-24 at 3 54 45 PM" src="https://user-images.githubusercontent.com/75148774/147310222-ccdd13a1-54aa-480c-a080-11ec83066e24.png">
Is this good

**Comment by JaydenDev** [comment]
The action bar is 

The search bar, forward and back buttons as well as reload. and every other button on that bar

The tab bar is above, with the tabs

Terminoligy

**Comment by webdev03** [comment]
Terminology*

**Comment by JaydenDev** [comment]
> <img alt="Screen Shot 2021-12-24 at 3 54 45 PM" width="1023" src="https://user-images.githubusercontent.com/75148774/147310222-ccdd13a1-54aa-480c-a080-11ec83066e24.png">
> Is this good

One thing i must say, you aren't on the latest commit.
Half that amount of space is good, then show me.

**Comment by webdev03** [comment]
Hmm, what do you mean? That's already quite a good amount of spacing in my opinion.

**Comment by JaydenDev** [comment]
its just a bit much

**Comment by JaydenDev** [comment]
a little smaller amount then ur good

**Comment by JaydenDev** [comment]
also get on the latest commit before doing any PRs.

**Comment by webdev03** [comment]
Well, ok...

**Comment by webdev03** [comment]
<img width="1023" alt="Screen Shot 2021-12-24 at 3 57 00 PM" src="https://user-images.githubusercontent.com/75148774/147310385-5c764c52-d3ac-4da2-8084-865311007606.png">
Is this good? Then I will update to the latest commit and redo my changes.

**Comment by JaydenDev** [comment]
@webdev03 yes thats good, I can handle the updating for you with the PR.

**Comment by webdev03** [comment]
Ok, if you say so...

**Comment by JaydenDev** [comment]
@webdev03 i made a PR.

**Comment by JaydenDev** [comment]
now im testing if it worked

**Comment by webdev03** [comment]
:smile:

**Comment by JaydenDev** [comment]
@webdev03 its weird that it didnt bring my commit where I fixed color consistancy

**Comment by JaydenDev** [comment]
@webdev03 oh it got undone... my color consistancy fix. im redoin it now.

**Comment by JaydenDev** [comment]
i redid the color consistancy fix.
now time to move into memory optimization

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147311080-28509969-e249-4e4d-bf6a-d54ab0791050.png)

so far this is what we have

**Comment by webdev03** [comment]
Yes, that looks much better, https://github.com/JaydenDev/Catalyst/issues/70#issuecomment-1000625503 I didn't think of it before.

**Comment by JaydenDev** [comment]
if the browser hogs 2x as much RAM as chrome there's a problem.

**Comment by webdev03** [comment]
Wait, it does? Hmm...

**Comment by JaydenDev** [comment]
When you hit 7 tabs it gets slow, could just be because I didn't test with a compiled version

**Comment by webdev03** [comment]
yes, compiled versions are much better.

**Comment by JaydenDev** [comment]
I test with npm since I can't install Catalyst without removing ninetails

**Comment by webdev03** [comment]
😢

**Comment by JaydenDev** [comment]
@webdev03 might use the "feature" to gain some ground.

**Comment by webdev03** [comment]
Which feature? Also, it would be more organised if there was a separate issue about memory. I'll make it.

**Comment by JaydenDev** [comment]
@webdev03 no no its already made check issues

**Comment by JaydenDev** [comment]
I've been using Catalyst for 5 minutes and its, good.

**Comment by webdev03** [comment]
:smile:

**Comment by JaydenDev** [comment]
Color inconsistincy in light mode
Also unlike FF or Chrome, there is no right click spell check/fixing to fix my spelling mistakes

**Comment by JaydenDev** [comment]
Unfortunately I can't even claim credit for most the browser, I coded like 3% of it.

**Comment by webdev03** [comment]
I will fix the colour inconsistency.
![image](https://user-images.githubusercontent.com/75148774/147313138-1a3c6dcf-217d-4b62-a5a3-9f32ce6b32c1.png)
You did quite a lot, and you've managed it too!

**Comment by JaydenDev** [comment]
Also, can the text in the search bar update per tab?
i have 1 gh tab and 1 scratch tab and no matter what tab im in it shows the github URL.

**Comment by webdev03** [comment]
Yes, that is something I was going to do too.

**Comment by JaydenDev** [comment]
@webdev03 I pretty much did the small tweaks

**Comment by JaydenDev** [comment]
so, most browsers dont require a button press to search. So, we can replace the "Go" button with an event listener, that runs the function the button would usually run. When ENTER is pressed.

**Comment by webdev03** [comment]
Yes, I am going to add the event listener too. I don't see any inconsistency, though!

**Comment by JaydenDev** [comment]
@webdev03 you need to look REAL closely in light mode

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147313455-458bbbc7-0e44-4c5f-83cd-482d8482cc4a.png)

**Comment by webdev03** [comment]
> @webdev03 you need to look REAL closely in light mode

How closely? Can you send a screenshot?

**Comment by JaydenDev** [comment]
zoom in quite a bit in my screenshot

**Comment by webdev03** [comment]
Can't see on my screen...

**Comment by JaydenDev** [comment]
the tab and action bar background is gray while the background background is white.

**Comment by JaydenDev** [comment]
its an easy fix i can do myself if i need to

**Comment by webdev03** [comment]
> the tab and action bar background is gray while the background background is white.

Oh, so that's what you mean! I'll add that in.

**Comment by JaydenDev** [comment]
should they both be white or both be gray? @webdev03

**Comment by webdev03** [comment]
I made it both gray, although I would kind of like it both white though.

**Comment by JaydenDev** [comment]
k

**Comment by JaydenDev** [comment]
Should I just release 1.0 next week instead of a pre-release?

**Comment by webdev03** [comment]
Maybe closer until the time we can decide?

**Comment by JaydenDev** [comment]
android app?
JK, NEVER NO NEVER DOING THAT PLEASE IGNORE

**Comment by webdev03** [comment]
> android app? JK, NEVER NO NEVER DOING THAT PLEASE IGNORE

I'm going to share my _maybe controversial_ opinion: in the future, an app may be possible.

**Comment by JaydenDev** [comment]
sorry if i dont respond for a while im hosting a web server on my phone... :)

**Comment by webdev03** [comment]
I guess we can release 1.0 soon. I can try to implement bookmarks. But when there are too many bookmarks, should there be a scrolling bar?

**Comment by JaydenDev** [comment]
@webdev03 I hate scroll bars, they are so ugly.

also note when i said that tab size or search bar size would have to be cut in half for bookmarks to not take up too much space.

**Comment by webdev03** [comment]
I think bookmarks can be implemented later. Right now I want to trim down the number of Font Awesome icons in the code.

**Comment by JaydenDev** [comment]
> I think bookmarks can be implemented later. Right now I want to trim down the number of Font Awesome icons in the code.

How else will there be icons then

**Comment by webdev03** [comment]
I am going to switch to bootstrap icons if that is fine with you... or should I instead trim down the number of FA icons? I think Bootstrap Icons is open source.

**Comment by JaydenDev** [comment]
Just download the icons into the repository into the assets folder and apply them in the UI

**Comment by webdev03** [comment]
Then, when building, even the icons we don't need are there.

**Comment by JaydenDev** [comment]
> Then, when building, even the icons we don't need are there.

What?

**Comment by webdev03** [comment]
Yeah, so there is going to be let's say 1000 icons in the build, but we use like 7 out of them.

**Comment by JaydenDev** [comment]
@webdev03 just download the icons that are needed and store them in the repo.

**Comment by webdev03** [comment]
That's what I am doing.

**Comment by JaydenDev** [comment]
so far my package manager's catalyst install script is working.
its for linux only tho, boxpkg is linux only

**Comment by JaydenDev** [comment]
nevermind its not working yet cuz syntax error

**Comment by JaydenDev** [comment]
```
run/catalyst-install.sh: line 11: cd: x64: No such file or directory
/usr/bin/apt
/usr/bin/rpm
run/catalyst-install.sh: line 23: syntax error near unexpected token `fi'
run/catalyst-install.sh: line 23: `fi'
```

**Comment by webdev03** [comment]
Put it on Homebrew soon! That would be **awesome**!

**Comment by JaydenDev** [comment]
I fixed everything but the last two errors.

**Comment by JaydenDev** [comment]
@webdev03 cant do that not on mac.

**Comment by webdev03** [comment]
> @webdev03 cant do that not on mac.

I could, when we hit 1.0

**Comment by JaydenDev** [comment]
for now focus on what ur doin and fixing the boxpkg catalyst install script.
just some syntax errors with the last two functions.

**Comment by webdev03** [comment]
I don't know much bash.

**Comment by JaydenDev** [comment]
@webdev03 I can't make a PPA without being on Ubuntu, and making a fedora repo is hard.

**Comment by JaydenDev** [comment]
also making a package manager is fun

**Comment by webdev03** [comment]
Anyways, this is `JaydenDev/Catalyst`.

**Comment by JaydenDev** [comment]
i fixed all the errors and now im testing it.

**Comment by webdev03** [comment]
Also, why build on the user's machine? There is a releases API and a page for that.

**Comment by JaydenDev** [comment]
no no, im doing it the only way i can do it with bash

**Comment by JaydenDev** [comment]
plus package managers are superior when they build from source

**Comment by JaydenDev** [comment]
All the features in Catalyst right now, will be in 1.0. Features discussed and made, closing.

**Comment by webdev03** [comment]
Wait, so right now, is 1.0 ?
