### ISSUE TITLE
1.0, bug fixes and stability

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#76]
Collaborate here for preparation for 1.0, fix bugs and stability issues.

Goals:
- Memory Optimization (Right now 7 tabs uses a LOT of RAM)

**Comment by webdev03** [comment]
Yes, in Neocruzr I was going to make some advanced memory optimisation, but I had to stop the fork.

**Comment by JaydenDev** [comment]
> Yes, in Neocruzr I was going to make some advanced memory optimisation, but I had to stop the fork.

In Catalyst, memory gets eaten up quickly and inefficiently.

**Comment by webdev03** [comment]
Anyone wants bookmarks?

**Comment by JaydenDev** [comment]
Sure you can make bookmarks

**Comment by JaydenDev** [comment]
@webdev03 
everyone, continue to clean up and fix bugs. Release 1.0 is near! It will release tomorrow on Christmas! If i'm able to anyway, its more likely to be on the 26th.

**Comment by webdev03** [comment]
Ok! What are some bugs that I can fix?

**Comment by JaydenDev** [comment]
@webdev03 well I haven't found any yet.

**Comment by webdev03** [comment]
I can make a cool welcome animation for Catalyst.

**Comment by JaydenDev** [comment]
@webdev03 well you keep talking about start up times...

**Comment by webdev03** [comment]
Startup time is fine.

**Comment by JaydenDev** [comment]
@webdev03 my laptop has a celeron and 4GB of RAM, please don't.

**Comment by webdev03** [comment]
At this rate when you come back we might actually be able to release 1.0 :smile:

**Comment by JaydenDev** [comment]
@webdev03 let me know when you have everything finished committed and merged. So I can eventually release 1.0

**Comment by JaydenDev** [comment]
@webdev03 Can you the action bar and the bookmark bar all the same size as the tab bar

**Comment by JaydenDev** [comment]
right now those buttons and bars take way too much space where content could be.

**Comment by webdev03** [comment]
@JaydenDev Hello

**Comment by webdev03** [comment]
I have got a bug you may not have noticed, and I really would like a fix.
Basically, if there are too many preferences or the screen is small, then the scroll will be cut off where it says "bookmarks" and I need a fix.

**Comment by JaydenDev** [comment]
@webdev03 I can't comprehend what you are saying, plus how do I fix a bug in YOUR code?

**Comment by JaydenDev** [comment]
I'm not a UI professional either

**Comment by JaydenDev** [comment]
plus, why are you actually using Catalyst lol.

**Comment by JaydenDev** [comment]
@webdev03 explain the bug in a new issue.
just know it wont be fixed before 1.0 :)

**Comment by webdev03** [comment]
OK.

**Comment by webdev03** [comment]
I'm not actually using Catalyst (I use firefox until passwords gets implemented which I can try to do) but when I was testing settings I found that.

**Comment by webdev03** [comment]
By the way, you own the repo, and you are the only one who is allowed to write to the repository.

**Comment by JaydenDev** [comment]
@webdev03 it'll get fixed in 1.1/ 21.12-fix01/21.12.110

**Comment by webdev03** [comment]
Don't make the tag name `21.12-fix01` or else.. :smile:

**Comment by JaydenDev** [comment]
@webdev03 when the bug fixes roll out it'll be labeled as 1.1.0

**Comment by JaydenDev** [comment]
btw the 1.0 win64 build is taking a while...

**Comment by webdev03** [comment]
1.0.0 right?

**Comment by webdev03** [comment]
LOL, Github Actions is broken, doesn't want to checkout.

**Comment by JaydenDev** [comment]
hmm it'll use the latest source right? thats fine.

**Comment by webdev03** [comment]
Should use the latest source, if you made the tag on the latest master branch.

**Comment by JaydenDev** [comment]
so the build is working, go check out 1.0!

**Comment by JaydenDev** [comment]
it failed to upload the file cuz i already published the release. oh well!

**Comment by webdev03** [comment]
Yeah, ok, I'll just `npm run dev` for now. We can close this!
