### ISSUE TITLE
Memory optimisations

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#78]
Improve the memory consumption of Catalyst.

**Comment by JaydenDev** [comment]
#76

**Comment by webdev03** [comment]
That's for bug fixes and stability. RAM consumption is fine, it still works. But it is something that in the future we may need to consider. Here is where we can plan for the future.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147311600-a868e17e-2892-4c7d-9662-dee0819ef691.png)
uhh

**Comment by JaydenDev** [comment]
the buttons got pushed where i cant see em

**Comment by webdev03** [comment]
2gb of ram, while using it for 5 tabs. I guess you kind of have a point now.

**Comment by webdev03** [comment]
I've never seen that happen before. Let's discuss that in a new issue.

**Comment by webdev03** [comment]
Actually, my "2gb calculation" was actually how much all of the applications I had on was using. In reality, it might actually be.. les...

**Comment by JaydenDev** [comment]
it sits around 128 MB of RAM.

**Comment by webdev03** [comment]
128? Isn't that way less than Chrome and Firefox?

**Comment by JaydenDev** [comment]
@webdev03 my testing was on the non-compiled version, the compiled is way faster

**Comment by webdev03** [comment]
So we can close this?
