### ISSUE TITLE
Add and Delete tab buttons go off screen when lots of tabs open.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#79]
![image](https://user-images.githubusercontent.com/92550746/147311664-789235d9-3f9c-4915-8a86-901f300b6519.png)

**Comment by webdev03** [comment]
Yes, I'll see how the flex container works.

**Comment by JaydenDev** [comment]
@webdev03 this is the latest compiled ver 21.12.106-beta, maybe you did fix it.

**Comment by webdev03** [comment]
I've got a fix, made a fix...

**Comment by JaydenDev** [comment]
It isn't fixed in the latest commits, so yeah make a PR.

**Comment by JaydenDev** [comment]
whats the command for a new release ugh. that one git push command i cant remember.

**Comment by webdev03** [comment]
`git push --follow-tags` :smile:

**Comment by JaydenDev** [comment]
resolved
