### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#83]
Catalyst Bookmarks
(FYI: No help needed right now, already made #91)

**Comment by JaydenDev** [comment]
@webdev03 ping
@webdev03 pong

how is the bookmark development going?

**Comment by JaydenDev** [comment]
@webdev03 if you want to make bookmarks you must either cut the tab size in half or the search bar size in half.

**Comment by webdev03** [comment]
Hey I went to sleep and today is Christmas. I am a living human being by the way

**Comment by JaydenDev** [comment]
Understood, I will stop pinging.

**Comment by JaydenDev** [comment]
I completely forgot about time zones, oof.

**Comment by JaydenDev** [comment]
well btw I wont be actively working on Catalyst starting today at 6PM CST all the way to December 26th. (Central standard time)

**Comment by webdev03** [comment]
Okay, so what should I do on the meantime?

**Comment by JaydenDev** [comment]
@webdev03 Well it doesn't start til 6 CST ( my time zone) for me its 3PM rn (December 24th)

**Comment by webdev03** [comment]
Started development on Bookmarks. I hope I can get a working version until you come back from your Christmas break. I hope you will enjoy it!

**Comment by webdev03** [comment]
@JaydenDev when you are back, tell me if you either want
<img width="758" alt="Screen Shot 2021-12-25 at 5 35 55 PM" src="https://user-images.githubusercontent.com/75148774/147377480-3e547fe0-f287-477e-a18f-8cfde4995285.png">
or optional bookmarks. For now, I'll add both, tell me which one you like, or ask the community!

**Comment by webdev03** [comment]
Bookmarks are going quite well! I'll push my changes and make a draft. Just got to make it so that you can add some to the list.

**Comment by webdev03** [comment]
Okay, I think they are ready to merge, I might make a few minor changes though, like if there are no bookmarks, hide the bookmarks bar.
