### ISSUE TITLE
Development Freeze, Today at 6:00 PM CST to December 26th

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#88]
I will not be working on Catalyst Today at 6PM CST, to December 26th as I will not be available during this period (Christmas).

Feel free to make PRs and issues and discuss features with other developers during this period, I will merge and confirm ideas afternoon December 26th.

**Comment by webdev03** [comment]
Merry Christmas!

**Comment by JaydenDev** [comment]
The period of the development freeze has ended, development will continue.

**Comment by webdev03** [comment]
Well, it didn't really freeze, I was working on bookmarks
