### ISSUE TITLE
Double Lines in the Bookmarks Bar?

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/Catalyst#94]
![image](https://user-images.githubusercontent.com/92550746/147413188-b5f5fb1b-cb3f-40b0-9e14-657dfadb515f.png)
Most of the time the bookmark text will take 2 lines, increasing the size of the bar
__decreasing the size of the webview__

**Comment by JaydenDev** [comment]
@webdev03

**Comment by webdev03** [comment]
Yes, I have no idea how to fix that...

**Comment by webdev03** [comment]
How is this `bug`, `enhancement`, and `question`?

**Comment by JaydenDev** [comment]
@webdev03 enhancing the browser by leaving more space for content :)

**Comment by webdev03** [comment]
@JaydenDev WHY did you put characters in the tag name? Now the auto updator will break! I told you this before.

**Comment by JaydenDev** [comment]
Dude, you realize it works just fine right

**Comment by webdev03** [comment]
Yes, I have no idea how to fix this, I'll work a bit more.

**Comment by webdev03** [comment]
I've got a fix, please wait while I finish it up and open PR.
