### ISSUE TITLE
Scroll cutoff in Preferences

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#97]
If you drag the window and make it smaller, then open settings, then you can scroll down, but then it is cut off where it says "bookmarks".

**Comment by JaydenDev** [comment]
I will start working on 1.1 tomorrow, @webdev03

**Comment by webdev03** [comment]
I can work on it now.

**Comment by JaydenDev** [comment]
@webdev03 literally just released 1.0 tho, take a break.

**Comment by webdev03** [comment]
Ok! But I'm quite bored right now.

**Comment by JaydenDev** [comment]
@webdev03 fineeeeee

**Comment by webdev03** [comment]
No, it's fine, you can add `On Hold`.

**Comment by webdev03** [comment]
May/may not be resolved. Please test.

**Comment by JaydenDev** [comment]
This bug will unfortunately never be fixed :/

**Comment by JaydenDev** [comment]
Neither 1.1 or 2.0 will be ever releasing.
Thank you everyone for your contributions but I will be killing the Catalyst project, forever. I will be archiving soon, if you like Catalyst please either go to Ninetails or another Electron browser.

**Comment by JaydenDev** [comment]
So is this bug gonna get fixed before Scottish Fold releases?

**Comment by webdev03** [comment]
This bug may not be fixed, I think somebody with a bit more CSS experience could help.

**Comment by JaydenDev** [comment]
@webdev03 you and I and velocity are currently the only people working on Catalyst at the moment. With a few others making bug reports.

**Comment by webdev03** [comment]
This bug may not be fixed, I think somebody with a bit more CSS experience could help.

**Comment by webdev03** [comment]
@JaydenDev could you fix this?

**Comment by JaydenDev** [comment]
> @JaydenDev could you fix this?

idk why you're asking me

**Comment by webdev03** [comment]
maybe because you are the "repository maintainer"?
