### ISSUE TITLE
Password Manager

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/Catalyst#98]
If I figure out how to get AES working, I could try to implement this.
Or we can store the passwords as plaintext I guess. Which one? AES is hard, and it will require the user to input a password every time, but more secure. Plaintext is less secure, but more convenient.

**Comment by JaydenDev** [comment]
Plain text is fine, just don't have anyone accidentily upload it on a git push. No hacker is gonna bother.

**Comment by webdev03** [comment]
@JaydenDev can I please be assigned?
It will be stored in localStorage, don't know what other to use, as localStorage should theoretically be fine.

**Comment by webdev03** [comment]
Why is it `On Hold`? I can do it right at this instant!

**Comment by JaydenDev** [comment]
@webdev03, take a break man.

**Comment by webdev03** [comment]
Ok!

**Comment by webdev03** [comment]
Data structure(?):
`
{
  "google.com": [
      {
         "user": "abc",
         "pass": "def"
      },
      {
         "user": "one",
         "pass": "two"
      }
   ],
   "scratch.mit.edu": [
      {
         "user": "1234",
         "pass": "5678"
      },
      {
         "user": "myuser",
         "pass": "mypass"
      }
   ]
}
`

**Comment by JaydenDev** [comment]
> Data structure(?):
> ```json
> {
>   "google.com": [
>       {
>          "user": "abc",
>          "pass": "def"
>       },
>       {
>          "user": "one",
>          "pass": "two"
>       }
>    ],
>    "scratch.mit.edu": [
>       {
>          "user": "1234",
>          "pass": "5678"
>       },
>       {
>          "user": "myuser",
>          "pass": "mypass"
>       }
>    ]
> }
> ```

Good enough

**Comment by webdev03** [comment]
How to access the webview DOM?

**Comment by JaydenDev** [comment]
@webdev03 you have to detect when someone has clicked log in on an login screen.

**Comment by webdev03** [comment]
I need to get access to the DOM first!

**Comment by webdev03** [comment]
I've been doing some research, and I've come to the conclusion, that the only way to do this is to execute javascript on the webview through `executeJavascript` to get access to the DOM. It is a bit hacky, though, and we won't be able to get any data back, so I think that this can be considered for later.

**Comment by JaydenDev** [comment]
@webdev03 for now just let users manually put their password in the manager, and have it copy-able to be put into a website.

**Comment by JaydenDev** [comment]
Can't hold up 1.1 too long over 2 days :)
bugs to fix

**Comment by webdev03** [comment]
Bugs to fix? `1.0.1` would be a nice name, instead of `1.1.0`

**Comment by JaydenDev** [comment]
> Bugs to fix? `1.0.1` would be a nice name, instead of `1.1.0`

That's stupid

**Comment by webdev03** [comment]
1.0.1 is a "patch release" to fix bugs. 1.1.0 may add features.

**Comment by JaydenDev** [comment]
@webdev03 2.0 adds features 1.0.1 is a patch release

**Comment by JaydenDev** [comment]
Like releases, bug fix releases have builds as well

**Comment by webdev03** [comment]
Ok. Sure.

**Comment by JaydenDev** [comment]
@webdev03 since I can't use text indication of different build channels I'll have to add more numbers to builds
Need a way to differentiate

**Comment by JaydenDev** [comment]
anyway I'll be back tomarrow.

**Comment by webdev03** [comment]
You can add them, I've come to the conclusion, prereleases have no auto updating functionality, and that is now going to be what happens I guess.

**Comment by webdev03** [comment]
I've successfully made a more menu myself without stealing code from ninetails (although I did check a few online resources like tailwind ui preview for some ideas). I'll make a PR for that, then once you merge it, I'll start working on passwords.

**Comment by FunctionalMetatable** [comment]
> @webdev03 2.0 adds features 1.1.0 is a patch release Like Chrome or FF
> 

no

node versioning (what you are supposed to be using because electron)

```
M.F.P
```
M = Major (for breaking changes, dramatic changes like whole rewrite)
F = Feature (For new features)
P = Patch (for bug fixes)

you should use this pattern or npm/pnpm/yarn will throw errors one day

**Comment by JaydenDev** [comment]
> > @webdev03 2.0 adds features 1.1.0 is a patch release Like Chrome or FF
> > 
> 
> no
> 
> node versioning (what you are supposed to be using because electron)
> 
> ```
> M.F.P
> ```
> M = Major (for breaking changes, dramatic changes like whole rewrite)
> F = Feature (For new features)
> P = Patch (for bug fixes)
> 
> you should use this pattern or npm/pnpm/yarn will throw errors one day
> 
> Chrome/Firefox would use F.P, which would throw errors if used in package.json
> 
> But tbh, @webdev03 is correct.

I don't have to use the same order, just some characters i can't use, but guess what it works so why does it matter

**Comment by JaydenDev** [comment]
soo....

**Comment by webdev03** [comment]
You should use the same order. Please? Otherwise it will break in the future.

**Comment by JaydenDev** [comment]
> You should use the same order. Please? Otherwise it will break in the future. @JaydenDev @JaydenDev

No, the older of numbers DOES NOT MATTER. The only time it will break is if I put in letters, which numbers aren't. Stop being stupid, be realistic. Or your PRs and issues will be ignored. Stop spam pinging me as well.

**Comment by webdev03** [comment]
Ok, sorry...

**Comment by JaydenDev** [comment]
@webdev03 not being stupid is a strict rule

Think about it, why would number order matter?
1.1.1 over 1.0.1 what will this break? nothing! THINK!

**Comment by webdev03** [comment]
Ninetails uses it.

**Comment by JaydenDev** [comment]
> Ninetails uses it. Ok sorry

What? Ninetails uses it so if I don't use their version method it'll break? Lol, great logic.

**Comment by webdev03** [comment]
"Chrome/Firefox would use F.P, which would throw errors if used in package.json"
"you should use this pattern or npm/pnpm/yarn will throw errors one day"

**Comment by webdev03** [comment]
Anyways, this is password manager, so I'll stop.

**Comment by webdev03** [comment]
I'll make a branch `passwords` and then make a draft PR.

**Comment by JaydenDev** [comment]
> I'll make a branch `passwords` and then make a draft PR. It's because I don't want any bugs to be in master. If you don't want me making branches, tell me and I'll delete it.

making extra branches is stupid, commit to master

**Comment by webdev03** [comment]
Fine, I'll do it on my own fork.

**Comment by webdev03** [comment]
https://www.toolsqa.com/git/branch-in-git/ is why I use branches

**Comment by JaydenDev** [comment]
@webdev03 its stupid tho, I don't want none of that clutter.

**Comment by webdev03** [comment]
You can delete branches after they are merged, but fine, I'll work on my fork............... 😕

**Comment by JaydenDev** [comment]
> You can delete branches after they are merged, but fine, I'll work on my fork............... confused

why are you so against commiting directly to master. I can revert commits if I need to.

**Comment by webdev03** [comment]
Why is this necessary? You can use another program for this purpose.

**Comment by JaydenDev** [comment]
> Why is this necessary? You can use another program for this purpose.

because I use, many use, everyone uses browser password managers. All the password managers not including browsers are PAID.

**Comment by hello-smile6** [comment]
> > Why is this necessary? You can use another program for this purpose.
> 
> because I use, many use, everyone uses browser password managers. All the password managers not including browsers are PAID.

Not all of them are.

**Comment by JaydenDev** [comment]
> > > Why is this necessary? You can use another program for this purpose.
> > 
> > 
> > because I use, many use, everyone uses browser password managers. All the password managers not including browsers are PAID.
> 
> Not all of them are.

all of them are

**Comment by hello-smile6** [comment]
> > > > Why is this necessary? You can use another program for this purpose.
> > > 
> > > 
> > > because I use, many use, everyone uses browser password managers. All the password managers not including browsers are PAID.
> > 
> > 
> > Not all of them are.
> 
> all of them are

Hmm, https://wiki.archlinux.org/title/GNOME/Keyring

**Comment by JaydenDev** [comment]
> > > > > Why is this necessary? You can use another program for this purpose.
> > > > 
> > > > 
> > > > because I use, many use, everyone uses browser password managers. All the password managers not including browsers are PAID.
> > > 
> > > 
> > > Not all of them are.
> > 
> > 
> > all of them are
> 
> Hmm, https://wiki.archlinux.org/title/GNOME/Keyring

thats not what you think it is, also off topic. I'll have to make the password manager myself if nobody else will.

**Comment by webdev03** [comment]
JaydenDev you can make the manager yourself.

**Comment by JaydenDev** [comment]
> JaydenDev you can make the manager yourself.

that means it'll never exist, or if it does manage to exist it'll be complete crap

**Comment by webdev03** [comment]
I've been doing a lot of work in this repository and I have spent hours. But you need to learn what your project is all about.

**Comment by JaydenDev** [comment]
```html
<input id="passwd" placeholder="password">
<input id="usr" placeholder="user">
<button onClick="saveLogin()">save</button>
```

**Comment by JaydenDev** [comment]
thats the best I can do :/

**Comment by JaydenDev** [comment]
This feature isn't happening, closing.

**Comment by hello-smile6** [comment]
> This feature isn't happening, closing.

Maybe make a `cantfix` label?

**Comment by webdev03** [comment]
`wontfix`

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147603919-7ee830d3-8156-4df6-80f4-ff72a513ed47.png)
how to make click werk

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/147603919-7ee830d3-8156-4df6-80f4-ff72a513ed47.png) how to make click werk

```javascript
let domNode=document.querySelector("#theElement");
domNode.addEventListener("click",function() {
  // Whatever you need to do
});
```
Does that help?

**Comment by JaydenDev** [comment]
@hello-smile6 @webdev03 made the code, so I'm asking him, I'm not asking the person who broke FreeCat twice.

**Comment by hello-smile6** [comment]
Make sure to encrypt stored passwords.
https://cryptojs.gitbook.io/docs/

**Comment by JaydenDev** [comment]
@hello-smile6 passwords can and will only be stored temporarily in the user's session. The password and username in the input boxes will be stored as variables that are only temporary.

**Comment by hello-smile6** [comment]
> @hello-smile6 @webdev03 made the code, so I'm asking him, I'm not asking the person who broke FreeCat twice.

Fine. https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener I'm right, though.

**Comment by JaydenDev** [comment]
```js
function openPasswords() {
    window.open("passwords.html");
}
```
How's this function?

**Comment by JaydenDev** [comment]
well it doesn't work

**Comment by JaydenDev** [comment]
@webdev03 whats the ID of the webvieW?

**Comment by hello-smile6** [comment]
> @hello-smile6 passwords can and will only be stored temporarily in the user's session. The password and username in the input boxes will be stored as variables that are only temporary.

Yes, and that means any process running as root on the user's device will be able to easily access passwords for all users. Additionally, any process running with access to whatever file you're storing passwords in will also be able to get the user's passwords.

**Comment by JaydenDev** [comment]
I Need to use

```js
document.getElementById("webview-id").value = passwords.html
```

**Comment by JaydenDev** [comment]
@hello-smile6 I'm doing passwords to the best of my ability, sorry!

**Comment by hello-smile6** [comment]
> ```js
> function openPasswords() {
>     window.open("passwords.html");
> }
> ```
> 
> How's this function?

If you look at `main.js`, `window.open` is disabled.
https://github.com/JaydenDev/Catalyst/blob/master/main/main.js#L50-L54

**Comment by JaydenDev** [comment]
If you make me do passwords, expect them to suck.

**Comment by JaydenDev** [comment]
> > ```js
> > function openPasswords() {
> >     window.open("passwords.html");
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How's this function?
> 
> If you look at `main.js`, `window.open` is disabled. https://github.com/JaydenDev/Catalyst/blob/master/main/main.js#L50-L54

if the webview(s) dont have a specific ID and window.open is disabled how will I do passwords then?

**Comment by hello-smile6** [comment]
> I Need to use
> 
> ```js
> document.getElementById("webview-id").value = passwords.html
> ```

Um, I'm not sure how. Also, it'd be `src`, not `value`.

**Comment by JaydenDev** [comment]
> > I Need to use
> > ```js
> > document.getElementById("webview-id").value = passwords.html
> > ```
> 
> Um, I'm not sure how. Also, it'd be `src`, not `value`.

well whatever I cant do it anyway

**Comment by hello-smile6** [comment]
> > > ```js
> > > function openPasswords() {
> > >     window.open("passwords.html");
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > How's this function?
> > 
> > 
> > If you look at `main.js`, `window.open` is disabled. https://github.com/JaydenDev/Catalyst/blob/master/main/main.js#L50-L54
> 
> if the webview(s) dont have a specific ID and window.open is disabled how will I do passwords then?

Well, you could always look at how the Beaker web browser does it.
https://github.com/beakerbrowser/beaker

**Comment by hello-smile6** [comment]
If you want to try Beaker, https://beakerbrowser.com/install/

**Comment by JaydenDev** [comment]
Ok passwords are canceled. If you wanted that feature too bad.

**Comment by hello-smile6** [comment]
> Ok passwords are canceled. If you wanted that feature too bad.

Maybe it's possible.

**Comment by JaydenDev** [comment]
> > Ok passwords are canceled. If you wanted that feature too bad.
> 
> Maybe it's possible.

Not with my knowlege of Javascript its not.
